### ISSUE TITLE
Not able to remove the delay from flux script

### ISSUE THREAD

**Issue by gshif** [influxdata/influxdb#12200]
Updating task by setting `offset` field to `0s` or to and empty string (not sure if it is supported) will result in error: 
```
cannot update task without content
```

I am assuming that setting `offset` to `0s` should result in removing the `delay` option from flux script. 

- Create a task with `delay` option.
   - Request body:
```
{
  "flux": "option task = {name:\"task_urdfc\", cron: \"* * * * *\", delay: 15s} from(bucket:\"read_from_b_query_params\") |> range(start: -1h)", 
  "orgID": "0376c42cfa80c000", 
  "status": "active"
}
```

- Update created above task with `offset` = `0s`
   - Request body
```
{"offset": "0s"}
```

- Response:
```
{
  "code": "internal error", 
  "error": "cannot update task without content", 
  "message": "failed to update task"
}
```

**Comment by rbetts** [comment]
@gshif Per http://docs.internal/api/swagger/#tag/Tasks/paths/~1tasks~1{taskID}/get, `taskid`, `name`, and `flux` are all required fields.

**Comment by mark-rushakoff** [comment]
This will be fixed by https://github.com/influxdata/influxdb/issues/12288.

**Comment by docmerlin** [comment]
@gshif I think this is already done.

**Comment by gshif** [comment]
I can see that `offset` is removed from the flux script, but `offset` is still being returned by the response object.
 - Create task:
```
requests.post(http://localhost:9999/api/v2/tasks, data={"orgID":"03c7daed2e6cb000", "flux":"option task = {name:\"task_urdfc\", cron: \"* * * * *\", offset: 15s} from(bucket:\"FIoDnyQuI7e0\") |> range(start: -1h)", "status":"active"}, headers={'Authorization': u'Token mHeEEfFCbIZ6mzNh-FFDJ2PrmUnj1w1W-L58yY-ycqUQJV1Qt18CAJC6Q_ViwMEJxWSFPeTAB7RYlU1-0drM0w=='})
```

- Update task (remove offset from cron):
```
requests.post(http://localhost:9999/api/v2/tasks/03c7daed462cb000, data={"offset": "0s"}, headers={'Authorization': u'Token mHeEEfFCbIZ6mzNh-FFDJ2PrmUnj1w1W-L58yY-ycqUQJV1Qt18CAJC6Q_ViwMEJxWSFPeTAB7RYlU1-0drM0w=='})
```

It returns the following object
```
u'status': u'active', 
u'latestCompleted': u'2019-04-30T18:07:41Z', 
u'name': u'task_urdfc', 
u'links': {u'runs': u'/api/v2/tasks/03c7daed462cb000/runs', 
               u'logs': u'/api/v2/tasks/03c7daed462cb000/logs', 
               u'self': u'/api/v2/tasks/03c7daed462cb000', 
               u'labels': u'/api/v2/tasks/03c7daed462cb000/labels', 
               u'owners': u'/api/v2/tasks/03c7daed462cb000/owners', 
               u'members': u'/api/v2/tasks/03c7daed462cb000/members'}, 
u'labels': [], 
u'cron': u'* * * * *', 
u'flux': u'option task = {name: "task_urdfc", cron: "* * * * *"}\n\nfrom(bucket: "FIoDnyQuI7e0")\n\t|> range(start: -1h)', u'orgID': u'03c7daed2e6cb000', 
u'offset': u'15s', 
u'updatedAt': u'2019-04-30T18:07:41Z', 
u'org': u'ZyFJ5LE0CJ0n', 
u'authorizationID': u'03c7daed246cb001', 
u'id': u'03c7daed462cb000', 
u'createdAt': u'2019-04-30T18:07:41Z'
```

**Comment by docmerlin** [comment]
Thanks, I think I see what is happening.  Looks like a separate bug.  I will self-assign.

**Comment by stuartcarnie** [comment]
Investigate if this is still an issue

**Comment by lyondhill** [comment]
fixed in #14961

**Comment by gshif** [comment]
I am seeing the error `failed to decode request: cannot update task without content` when removing `offset`.
- Create task with `offset`. Request body : 
```
{"orgID":"512d2f5e662f3544", "flux":"option task = {name:\"task_urdfe\", every: 1m, offset: 15s} from(bucket:\"read_from_b_query_params\") |> range(start: -1h)", "status":"active"}'
```

- Update the created task. Request body:
```
{"offset": "0s"}
```

Returned error:
```
{u'message': u'failed to decode request: cannot update task without content', u'code': u'invalid'}
```

**Comment by kevinhogan111** [comment]
I'm still seeing this issue: 

I am seeing the error `failed to decode request: cannot update task without content` when removing `offset`.
- Create task with `offset`. Request body : 
```
{"orgID":"512d2f5e662f3544", "flux":"option task = {name:\"task_urdfe\", every: 1m, offset: 15s} from(bucket:\"read_from_b_query_params\") |> range(start: -1h)", "status":"active"}'
```

- Update the created task. Request body:
```
{"offset": "0s"}
```

Returned error:
```
{u'message': u'failed to decode request: cannot update task without content', u'code': u'invalid'}
```
