### ISSUE TITLE
Filtering on tags and values returns a limited number of rows in 1.x

### ISSUE THREAD

**Issue by affo** [influxdata/influxdb#13815]
See https://github.com/influxdata/flux/issues/1100

**Comment by nathanielc** [comment]
Is this fixed now that Flux has been updated in 1.x?

**Comment by affo** [comment]
I've tried to run a query that filters on values using the current available InfluxDB through  `brew` (InfluxDB `1.7.7`, Flux `0.24`), and the results were consistent. Closing the issue.

**Comment by FatihTaskent** [comment]
@affo , Unfortunately this issue still occurs in the current InfluxDB version (InfluxDb `1.8` with Flux `0.65`)
