### ISSUE TITLE
Rows getting truncated to 5000 results

### ISSUE THREAD

**Issue by kennyjwilli** [influxdata/influxdb#16684]
__Steps to reproduce:__
I have not yet created a minimal repro of this issue. Below are the approximate steps to reproduce this issue. 

1. Insert 6000 rows for the same time series.
2. Run this query: 
```
from(bucket:"my-bucket")
|> range(start:2020-01-01T00:00:00Z,stop:2020-01-25T00:00:00Z)
|> filter(fn: (r) => r["foo"] == "bar")
|> filter(fn: (r) => r["_value"] == true)
|> count()
```
That returns one row with the `_value` at 5000. 

3. Now remove the last two lines so the query looks like this:
```
from(bucket:"my-bucket")
|> range(start:2020-01-01T00:00:00Z,stop:2020-01-25T00:00:00Z)
|> filter(fn: (r) => r["foo"] == "bar")
```
4. Count the resulting number of rows that `_value` is equal to `true` and I get 5433. This is the correct answer yet the previous query returned 5000.

__Expected behavior:__
The total number of rows matching the filter are returned and taking into account by the aggregate. 

__Actual behavior:__
The number of rows returned is limited to 5000 even though no `limit` is set.  This results in an incorrect aggregate.

__Environment info:__

InfluxDB Cloud v2

**Comment by russorat** [comment]
@kennyjwilli thanks for opening this issue. I've assigned this to the Flux team to see if they can help figure out what's going on.

**Comment by nathanielc** [comment]
@kennyjwilli This issue has been fixed. I verified today that its working. Here is the PR that fixes it if you are curious https://github.com/influxdata/influxdb/pull/16600 There was also some other work that happened on the cloud side of things to get this fix all the way out. 

Can you confirm from your side of things that its working?

**Comment by kennyjwilli** [comment]
@nathanielc Sorry for the delay here. 

I'm still seeing some strange behavior. Running this query incorrectly returns 1000.

```
from(bucket:"my-bucket")
|> range(start:2020-01-04T00:00:00Z,stop:2020-02-18T00:00:00Z)
|> filter(fn:(r) => (r["_measurement"] == ":data-point.measurement/aws-workspace" and r[":application-spec/id"] == "abc123" and r[":monitored-aws-workspace/workspace-id"] == "id"))
|> filter(fn:(r) => (r["_field"] == ":data-point.field/aws-workspace-user-connected?" and r["_value"] == true))
|> count()
```

Running this query correctly returns 5521. 

```
from(bucket:"my-bucket")
|> range(start:2020-01-04T00:00:00Z,stop:2020-02-18T00:00:00Z)
|> filter(fn:(r) => (r["_measurement"] == ":data-point.measurement/aws-workspace" and r[":application-spec/id"] == "abc123" and r[":monitored-aws-workspace/workspace-id"] == "id"))
|> filter(fn:(r) => (r["_field"] == ":data-point.field/aws-workspace-user-connected?" and r["_value"]))
|> count()
```

You'll notice the only different between the two queries is `r["_value"] == true` versus `r["_value"]`.

**Comment by jacobmarble** [comment]
@kennyjwilli this should have been fixed in https://github.com/influxdata/influxdb/pull/16600 . Can you verify that recent beta releases still exhibit this behavior?

**Comment by jacobmarble** [comment]
@kennyjwilli I have built and run 2.0.0 beta 9 to test this. To me, things are working as intended. Can you recheck?
```
$ while true; do influx write -o my-org -b my-bucket "m,test=bool v=true" -t my-token; done
^C
$ influx query -o my-org 'from(bucket: "my-bucket") |> range(start: -24h) |> filter(fn: (r) => r["test"] == "bool")' | wc -l
    2446
$ influx query -o my-org 'from(bucket: "my-bucket") |> range(start: -24h) |> filter(fn: (r) => r["test"] == "bool") |> count()'
Result: _result
Table: keys: [_start, _stop, _field, _measurement, test]
                   _start:time                      _stop:time           _field:string     _measurement:string             test:string                  _value:int  
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  --------------------------  
2020-05-10T16:59:59.789123000Z  2020-05-11T16:59:59.789123000Z                       v                       m                    bool                        2442  
```

**Comment by kennyjwilli** [comment]
We aren't having this issue with the latest InfluxDB Cloud v2 so guessing it is resolved.
