### ISSUE TITLE
Unable to perform a tableFind within a Task

### ISSUE THREAD

**Issue by nroypf** [influxdata/influxdb#18922]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. create a bucket name : CHECKPOINT-0000_4000.01.000
2. create a task, name it : 'Invalidation task', every: 1m, offset: 30s
3. try to save this script
```
from(bucket: "CHECKPOINT-0000_4000.01.000")
	|> range(start: -task.every)
	|> filter(fn: (r) =>(r["_measurement"] == "CHECKPOINT"))
    |> tableFind(fn: (key) => key._field == "ts")
```

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
It returns an error:
> Failed to update task: failed to update task: invalid options; Err: error calling function "findColumn": no execution context for tableFind to use: error calling function "findColumn": no execution context for tableFind to use

__Environment info:__
Linux 4.15.0-1089-azure x86_64
Influx CLI 2.0.0-beta.14 (git: c8af0f35be) build_date: 2020-07-08T20:36:27Z

__Config:__

__Logs:__

__Performance:__

**Comment by ddemin** [comment]
Same issue for build [25461dd](https://github.com/influxdata/influxdb/commit/25461dddcde12c5871e28dc2225d118bb9b6e038), but as I see in Flux repository - a lot of context-related (for tableFind) issues are fixed already

**Comment by nroypf** [comment]
Still have the error (Cloud version) 
Failed to create new task: invalid options; Err: error calling function "tableFind": no execution context for tableFind to use: error calling function "tableFind": no execution context for tableFind to use

**Comment by abalone23** [comment]
I only get this error in OSS 2.0.3. It works fine in InfluxDB Cloud.

**Comment by russorat** [comment]
This is a dupe of https://github.com/influxdata/influxdb/issues/17666

**Comment by timhallinflux** [comment]
Needs a retest as part of 2.0.4.  It should have been resolved there.

**Comment by abalone23** [comment]
It doesn't work in OSS 2.0.4 and it doesn't work in today's nightly build either:
```
https://dl.influxdata.com/platform/nightlies/influxdb2_nightly_linux_amd64.tar.gz
```

**Comment by timhallinflux** [comment]
@psteinbachs -- this will need some investigation as to why Cloud and OSS are out of synch re: this capability.  Address as part of 2.0.5?

**Comment by danxmoran** [comment]
Closing this as a duplicate, please track #17666 for progress updates
