### ISSUE TITLE
InfluxDB OSS V2.0.1 Basic Authentication broken for InfluxDB 1.x clients

### ISSUE THREAD

**Issue by ggear** [influxdata/influxdb#20049]
Hi All,

I have just upgraded from v2.0.0-rc.4 to v2.0.1 and have noticed that Basic Authentication via the InfluxDB 1.x clients (including dumb HTTP clients) no longer works.

__Steps to reproduce__

Execute a query with basic authentication encoded into the URL:

```
curl -G --silent --request GET "http://influxdb:${INFLUXDB_TOKEN}@myhost:8086/query?db=test_bucket" --data-urlencode "q=SELECT count(*) FROM test_metric WHERE time >= now() - 15m"
```

__Expected behaviour__

In v2.0.0-rc.4 this succeeds:

```
{"results":[{"statement_id":0,"series":[{"name":"test_metric","columns":["time","count_test_value"],"values":[["2020-11-16T12:42:45.508120289Z",20]]}]}]}
```

__Actual behaviour__

In v2.0.1 this fails:

```
{"code":"unauthorized","message":"Unauthorized"}
```

__Impact and work arounds__

Note, that using Token Authentication does work in both v2.0.0-rc.4 and V2.0.1, but requires a V2 client or ability to modify client code.

This is major regression and break backwards compatibility for key Influx 1.x clients (this can be worked around in Grafana by adding the Token Auth Headers, but is not possible for typical clients that don't offer that level of configurability - the vast majority).

**Comment by danxmoran** [comment]
Hi @ggear, thanks for the report! There were a few auth-related bugs in rc.4 which allowed unauthed users to read/write data they shouldn't have had access to. I'm not sure if this is one of those cases, but to sanity-check could you confirm that:
1. The value of `${INFLUXDB_TOKEN}` is the raw (not encoded) password for user `influxdb`?
1. The user `influxdb` has been granted read permissions on the bucket `test_bucket/autogen`?

**Comment by ggear** [comment]
Hi @danxmoran.

Yes ${INFLUXDB_TOKEN} is the raw token copied from the Kapacitor UI, I did try a HTTP Header Basic version with both raw and base64 encoded user:token combination also but that did not work.

The influxdb user is the default user I setup on initial configuration, it has the 'owner' role. The token I am using is the default InfluxDB token and has complete permissions.

Thanks,
Graham

**Comment by danxmoran** [comment]
Thanks for the info @ggear, I have a hunch for what might be going on. One more question: Is the `test_bucket` DB you're trying to query a DB that was migrated from an existing V1 deployment using `influxd upgrade`? Or is it a fresh V2 bucket that you're trying to access via the V1 APIs?

**Comment by ggear** [comment]
The `test_bucket` is newly created in a fresh install, with a newly created DBRP mapping prior to data insert and query.

**Comment by danxmoran** [comment]
Hi @ggear the 2.0.2 release that just landed includes a few fixes and utilities for DBRP mappings. I wasn't able to reproduce the auth problem using its binaries, so hopefully the issue you ran into was fixed. I've listed the steps I used below, could you upgrade and check that it's also working for you?
```
# Setup fresh instance of 2.0.2
influx setup -o influx -b test_bucket -u influx-admin -p influxdb-admin -f

# Get the ID of the newly-created bucket
BUCKET_ID=$(influx bucket list -o influx -n test_bucket --json | jq -r '.[0].id')

# Create a DBRP mapping
influx v1 dbrp create -o influx --db test_bucket --rp default --default --bucket-id ${BUCKET_ID}

# Create a V1 auth token (use 'influxdb' as the password when prompted)
influx v1 auth create -o influx --username influxv1 --read-bucket ${BUCKET_ID}

# Query the new DBRP mapping.
# I get {"results":[{"statement_id":0}]}
curl -G --silent --request GET "http://influxv1:influxdb@localhost:8086/query?db=test_bucket" \
    --data-urlencode "q=SELECT count(*) FROM test_metric WHERE time >= now() - 15m"
```

**Comment by ggear** [comment]
Thanks @danxmoran, 2.0.2 seems to have resolved the issue, thanks so much!

Also, thanks for [ #20106](https://github.com/influxdata/influxdb/issues/20106), this will definitely help and means I can remove all my `expect` scripts for automated builds.

**Comment by szerwi** [comment]
I think I still experience this problem on 2.0.2
Here is the URL that I type in the browser:
`http://192.168.1.195:8086/query?pretty=true&u=influx&p=password.123&db=Stacja_pogodowa&q=SELECT+last("Temperature")+FROM+"ESP32"`
I get the unathorized response: `{"code":"unauthorized","message":"Unauthorized"}`
influx user is the owner of organization. As I understand, in p= I should put the user password (the same as in Influxdb 1.8), not the new authentication token? Actually, it is also not working using the token.

**Comment by danxmoran** [comment]
Hi @szerwi, what command did you use to create the user/pass combo? The V1 APIs only work with auths created using `influx v1 auth create`, and using the username/password of the V2 user created via `influx setup` or `influx user create` is expected to hit problems.

**Comment by szerwi** [comment]
@danxmoran Thank you for quick response. It is working perfectly after creating user using `influx v1 auth`. Thanks! :)
