### ISSUE TITLE
Intermittently missing Datapoints

### ISSUE THREAD

**Issue by Bharathebt** [influxdata/influxdb#20312]
Hi,

We've created a downsample Task and it fails intermittently with error
```
'Error exhausting result iterator; Err: runtime error @18:6-19:146: reduce: failed to evaluate reduce function: cannot convert argument of type invalid to float: runtime error @18:6-19:146: reduce: failed to evaluate reduce function: cannot convert argument of type invalid to float'.
```

Below is our Task code snippet:

```
calculateAttPerHour = (column, tables=<-, outputField="att") =>
	(tables
	  |> reduce(identity: {tc: 0.0, tt: 0.0, attph: 0.0}, fn: (r, accumulator) =>
               ({
                  tc: accumulator.tc + r.c,
                  tt: accumulator.tt + r.att * r.c,
                  attph: math.floor(x: (accumulator.tt + r.att * r.c) / (accumulator.tc + r.c))
                })
           )
       )

attph = from(bucket: "<bucket>")
	|> range(start: -1h)
	|> pivot(rowKey: ["_start", "_stop", "_time", "u", "f"], columnKey: ["_field"], valueColumn: "_value")
	|> aggregateWindow(every: 1h, fn: calculateAttPerHour, createEmpty: false)
```

When we checked the data for the failure, it's happening when datapoint for either att or c field is missing.

We use line protocol to write data to InfluxDB as below sample format 'measurement,u=<_userId>,f=<_flowId> c=230,att=478 timeInMilliseconds'. So datapoints for both fields 'c' and 'att' should present or both should miss. But with the task error and with our findings, datapoint for only one of the field(c or att) is missing.

Could you please let us know what could be the reason that some datapoints are missing intermittently.

__Expected behavior:__
Task should complete successfully.

__Actual behavior:__
Task is failing intermittently.

* InfluxDB version: Cloud 2.0

**Comment by jsternberg** [comment]
Hi @Bharathebt.

I'll be taking a look at the problem you are running into. If I may ask, are you still experiencing this problem and at what interval are points written in? Are the points written at random times (like events) or at a regular interval like every 10 seconds? For the row where a value is missing, is it the most recent or at a random time in the middle of the interval? Which cloud provider and region are you using?

To clarify something with this statement:

> We use line protocol to write data to InfluxDB as below sample format 'measurement,u=<_userId>,f=<_flowId> c=230,att=478 timeInMilliseconds'. So datapoints for both fields 'c' and 'att' should present or both should miss. But with the task error and with our findings, datapoint for only one of the field(c or att) is missing.

While line protocol will have these on the same line, these are still considered separate points by influxdb. After consulting with a member of the storage team, they told me that when `/write` returns it guarantees that the point will be persisted, but there can still be a small section of time when the point isn't yet readable or one point is readable and the other not yet. With some more information about the write pattern, we might be able to modify the flux script or find a way to make the task more resilient to this write/read lag.

**Comment by Bharathebt** [comment]
Hi @jsternberg, Thanks for responding. Below are my answers.

Are you still experiencing this problem and at what interval are points written in?
-- Yes. We have multiple processes which consume events and post them to InfluxDB every 30s.
   But the processes don’t follow the same time that is process 1's 30s window may differ from process 2's 30s window. So we can consider it as random.
For the row where a value is missing, is it the most recent or at a random time in the middle of the interval?
-- Its somewhere in the middle of the interval. The downsample task which we have works on a 2 hour old data.
Which cloud provider and region are you using?
-- For the InfluxDB cloud environment which we use the cloud provider is AWS and region is use-west-2.

**Comment by 8none1** [comment]
Hi @Bharathebt in parallel to @jsternberg's questions could you also provide me with your `org_id` and `bucket_id` for the bucket in question.  Rather than post those here you can email them to me wcooke@influxdata.com
We will run a tool to help us identify if there is a difference between the replicas of the data in your bucket and why that might be.

**Comment by philjb** [comment]
@Bharathebt - a few more question please:

You said that the downsample task runs on `2 hour old data`. The snippet you shared of the task shows `range(start: -1h)`, which is operating on the recent hour of data. Are you using the most recent hour or are you doing `range(start: -2h, stop: -1h)`?

How often is your task scheduled to run? Hourly?

If you are using `range(start: -1h)`, could you reconfigure your task to use the `offset` option of about 5 minutes and adjust the `range` in the task to use `task.every`? These settings will run your task with an offset delay but keep the input data on the hour boundaries. This will avoid the readability delay that @jsternberg explained. The documentation for these settings is here: https://docs.influxdata.com/influxdb/v2.0/process-data/get-started/#define-a-data-source

If you are still seeing the problem, please share the complete task (remove or change private information) instead of a snippet.

**Comment by Bharathebt** [comment]
Hi @philjb We already have offset of 2h in our task code and it scheduled to run every 1 hr and querying the data for last 1hr, which is task will pick the data between the last 3hr data and last 2hr data..

option task = {
	name: "flowEvents_downSample_DO_NOT_RUN_MANUALLY",
	cron: "0 * * * *",
	retry: 3,
	offset: 2h,
}

And we did some more debugging found some issues, first we wrote a query to identify the missing datapoints (i.e either field 'c' or 'att' is missing)

Query1: 
from(bucket: "flowEvents")
    |> range(start: -4d, stop: -1d)
    |> filter(fn: (r) => (r._measurement == "s"))
    |> pivot(rowKey: ["_start", "_stop", "_time", "u", "f", "ei"], columnKey: ["_field"], valueColumn: "_value")
    |> filter(fn: (r) => ((exists r.c and not exists r.att) or (exists r.att and not exists r.c )))

Here you can see, for few rows values for 'c' field is present but 'att' field is missing and sometimes 'c' is present and 'att' is missing (this should never happen as we write both c and att together to influx in one call as "measurement,u=<u>,f=<f>,ei=<ei> c=230,att=478 timeInMilliseconds").

![image](https://user-images.githubusercontent.com/8435616/104996906-b674f800-5a4e-11eb-9bd8-00192b0a2bde.png)

We went ahead and queried the data for that particular time range(2021-01-15T01:48:00.000Z) to check whether data is really missing.

Query2:
from(bucket: "flowEvents")
  |> range(start: -4d, stop: -1d)
  |> filter(fn: (r) => (r._measurement == "s"))
  |> filter(fn: (r) => (r.ei == "5e2a09ac9b9a4925f2f27ef3"))
  |> filter(fn: (r) => (r._time == 2021-01-15T01:48:00.000Z))

The query results were inconsistent i.e. sometimes it's returning only 'att' and sometimes it's returning both 'att' and 'c'.

![image](https://user-images.githubusercontent.com/8435616/104996961-d4425d00-5a4e-11eb-9d9b-962b915ff1fa.png)

![image](https://user-images.githubusercontent.com/8435616/104996982-dc9a9800-5a4e-11eb-8155-7d95a840b595.png)

Hence, it seems that the task is failing due to inconsistent query results and not due to missing data. Please verify if this is the reason and check further but from the debugging that we could do, it seems the query results are not consistent.

@8none1 With the above results, do you still require bucket_id and org_id, if yes I can mail you.

**Comment by 8none1** [comment]
@Bharathebt - yes please, email me the bucket_id and your org id.

**Comment by 8none1** [comment]
@Bharathebt - thank you for providing the information.  We've set up an account and are running tasks like yours to try and recreate the issue so that we can get this fixed.  Please bear with us.

**Comment by 8none1** [comment]
Hi @Bharathebt - we think that this should be resolved now.  Please could you rerun your queries and confirm that you are seeing consistent results now?

**Comment by Bharathebt** [comment]
Hi @8none1 We've run the query and it looks like the issue is still happening. 

We still get the datapoints ((c exists and att not exists) or (c not exists and att exists)) when we run Query1. The timestamp of those datapoints are of 24th and 25th date.

![image](https://user-images.githubusercontent.com/8435616/105966460-b4dcad00-60aa-11eb-99ef-fa4f5b7bbf5a.png)

Below are the Query2 results:

![image](https://user-images.githubusercontent.com/8435616/105966055-25cf9500-60aa-11eb-8225-6ed9aea17b20.png)

![image](https://user-images.githubusercontent.com/8435616/105966086-32ec8400-60aa-11eb-9274-12fe24279307.png)

**Comment by 8none1** [comment]
This is now fixed in InfluxDB and is rolling out to production now.  

Fixed via PR: https://github.com/influxdata/idpe/pull/9743#event-4420553541
