### ISSUE TITLE
Panic when creating v1 user mapping

### ISSUE THREAD

**Issue by hinst** [influxdata/influxdb#21760]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create an organization named TST
   1. `influx org create -n TST`
2. Create a bucket named FacilityDataPoint in organization TST
   1. `influx bucket create -o TST -n FacilityDataPoint`
3. Create a v1 (legacy) user mapping for bucket FacilityDataPoint
   1. `influx v1 auth create --org TST --read-bucket e646f2be346898be --username TST_FacilityDataPoint --password V7v4wwwwwwww`
4. Delete organization TST
   1. `influx org delete -i 9e8b11348ce7b39c`
5. Create organization named TST
   1. `influx org create -n TST`
6. Create a v1 (legacy) user mapping using the same command as before
   1. `influx auth create --org TST --read-bucket e646f2be366898be --username TST_FacilityDataPoint --password V7v4www`
   2. outcome -> `panic`

To sum it up, the key to reproducing the bug seems to be: use the same org name and user name after deleting the org

__Expected behavior:__
User mapping is created successfully

__Actual behavior:__
Error:
```
hinst@DESKTOP-SG5G2AJ:~/influxdb-app$ ./influx v1 auth create --org REI --read-bucket b388733c952e33ab --username REI_FacilityDataPoint --password V7v4KwKZduU5UxkK
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.v1FindOneAuthorization(0xc0006bf9f8, 0x7222fe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000c2400, 0x7f237c4fd0e8, 0xc0006bf940)
        /home/alex/Dev/influxdb_forked/cmd/influx/v1_authorization.go:547 +0x1e5
main.makeV1AuthorizationCreateE.func1(0xc00058fb80, 0xc0001a8f80, 0x0, 0x8, 0xc0005e6280, 0xc00019c120)
        /home/alex/Dev/influxdb_forked/cmd/influx/v1_authorization.go:116 +0x1ba
main.checkSetupRunEMiddleware.func1.1(0xc00058fb80, 0xc0001a8f80, 0x0, 0x8, 0x0, 0x0)
        /home/alex/Dev/influxdb_forked/cmd/influx/main.go:466 +0x74
github.com/spf13/cobra.(*Command).execute(0xc00058fb80, 0xc0001a8f00, 0x8, 0x8, 0xc00058fb80, 0xc0001a8f00)
        /home/alex/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000548580, 0x0, 0x0, 0xc000548580)
        /home/alex/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/alex/.gvm/pkgsets/go1.15/global/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/alex/Dev/influxdb_forked/cmd/influx/main.go:43 +0x58
```

__Environment info:__

* System info: `Linux 5.8.0-59-generic x86_64`
* InfluxDB version: `InfluxDB 2.0.7 (git: 2a45f0c037) build_date: 2021-06-06T19:17:40Z`
* Other relevant environment details: happens both with Linux and Windows builds

__Config:__
No special config

__Logs:__
`info   Failed to create auth response {"log_id": "0V0SXzj0000", "handler": "getAuthorizations"}`

**Comment by russorat** [comment]
seems to be an issue here: https://github.com/influxdata/influxdb/blob/v2.0.7/cmd/influx/v1_authorization.go#L547

**Comment by russorat** [comment]
also, you should create a new bucket when you create a new org, although the panic still happens.

**Comment by danxmoran** [comment]
The impl in the new CLI instead returns:
```
Error: failed to create new authorization: 422 Unprocessable Entity: token already exists
```
Closing this as fixed by influxdata/influx-cli#138

**Comment by Cougar** [comment]
The same `index out of range` problem is still there. I'm not sure how it exactly happened but most probably related with removing org (by mistake) and adding it back. I can't create a v1 auth ant more. I'm not sure if there is anything that can be "reset" or should I just reinstall everything? Many different `v1 auth` commands give this error. One example:

```
bash-5.1# influx version 
Influx CLI 2.0.8 (git: e91d41810f) build_date: 2021-08-13T18:22:30Z

bash-5.1# influx v1 auth set-password 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.v1FindOneAuthorization(0xc00031fc38, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa, 0x9, 0x9)
        /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/v1_authorization.go:544 +0x1f3
main.makeV1AuthorizationSetPasswordF.func1(0xc00041a580, 0x23e3e20, 0x0, 0x0, 0xc000417e00, 0xc00022f950)
        /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/v1_authorization.go:626 +0x110
main.checkSetupRunEMiddleware.func1.1(0xc00041a580, 0x23e3e20, 0x0, 0x0, 0x0, 0x0)
        /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:466 +0x76
github.com/spf13/cobra.(*Command).execute(0xc00041a580, 0x23e3e20, 0x0, 0x0, 0xc00041a580, 0x23e3e20)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002398c0, 0x0, 0x0, 0xc0002398c0)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/circleci/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:43 +0x58
```
