### ISSUE TITLE
v2.6.0: Failed to create API token

### ISSUE THREAD

**Issue by thn80** [influxdata/influxdb#23993]
Hello,

I already asked in the Influxdata forum [(Link),](https://community.influxdata.com/t/failed-to-create-api-tokens/27777) but except another user with the same problem, no answer so far.

I installed InfluxDB v2.6.0 and directly after the installation and running the initial configuration wizard via the Web UI I tried to create new API tokens.
However, all the time I get the error message “**Failed to create API tokens: authorizations cannot be created with the instance type, it is only used during setup**”.

Does someone have an idea what is going wrong?

Furthermore, when I create my admin user during the initial config wizard, there was NOT shown any admin token and after finishing the wizard there is no way to have a look on this token again. Is this a bug of InfluxDB v2.6.0?

Thanks,

Thomas

**Comment by jeffreyssmith2nd** [comment]
Hey thanks for the report.
> Failed to create API tokens: authorizations cannot be created with the instance type, it is only used during setup

This is a bug that was inadvertently introduced while attempting to fix another bug. It should be addressed in the next release. In the meantime, you should be able to create authorizations from the CLI by following the directions [here](https://github.com/influxdata/influxdb/issues/23668)

> there was NOT shown any admin token and after finishing the wizard there is no way to have a look on this token again. Is this a bug of InfluxDB v2.6.0?

Yes, this is a regression that needs to be addressed but is not as simple as the above. In the meantime, you should be able to go to the Auth page in the UI and clone the operator token that is created during setup. Alternatively, you can do setup through the CLI and it will be automatically set in your config file.

**Comment by abiriadev** [comment]
I encountered the same issue, and have solved it via influx CLI.
I think this is the best solution as of now.

**Comment by jeffreyssmith2nd** [comment]
v2.6.1 has been released which should resolve the inability to create an All Access Token. I'm going to close this issue, please feel free to open a new issue if any further issues are encountered.

**Comment by petersloan** [comment]
@jeffreyssmith2nd  I just tested this on a fresh install of v.2.6.1 straight from this repo and the issue still exists.  If I am not mistaken, the PR to fix this contains ONLY the version bump, no actual code changes.  I assume this was a mistake?

https://github.com/influxdata/influxdb/pull/24014/files/29b0cde6a2233258d4e0d3930c5705ab8c73b03c

**Comment by jeffreyssmith2nd** [comment]
All the code changes were on the UI side, so that should be all that is needed. Can you double check that you've done a hard refresh in your browser? Sometimes the UI asset cache can be pretty sticky.

**Comment by petersloan** [comment]
Thank you!  I have confirmed clearing site data will removed the cached assets and allow all access keys to be generated.  It wasn't clear this was UI only but rereading with hindsight, it makes sense.

**Comment by spkis** [comment]
I also have the issue with a fresh installation of v2.6.1.
I was able to use the cli but with the website no change. I also did create the databases from scratch and used a new browser window in incognito mode. 

would there be anything else to try to get this working in the UI Again?

**Comment by jeffreyssmith2nd** [comment]
Just to be sure, you're getting the exact `“Failed to create API tokens: authorizations cannot be created with the instance type, it is only used during setup”` message?

**Comment by spkis** [comment]
Hello Jeffrey,
Thanks for asking - no that’s not the message. It’s says about no permission to write.
Shall I just raise a new separate  ticket for it?

Mit elektrischen Grüßen
Ricardo Kissinger

Send from iPhone - excuse typos.
________________________________

**Comment by jeffreyssmith2nd** [comment]
Yes, a new issue would be best and any screenshots/logs you have that would further indicate the problem. Thanks!
