### ISSUE TITLE
cannot explicitly reference "default" retention policy in CQs

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb#3654]
From https://github.com/influxdb/influxdb/issues/3649#issuecomment-130872349

Leads to `error parsing query: found DEFAULT, expected identifier at line 1, char 89`

I have not tried to repro myself.

**Comment by DanielMorsing** [comment]
May have been fixed by #3560

**Comment by beckettsean** [comment]
Still getting the error in latest nightly (0.9.3-nightly-1548f62)

**Comment by jsternberg** [comment]
This should now be possible by using double quotes to surround the identifier. Please reopen if this is still a problem. Thanks.
