### ISSUE TITLE
[0.10.0-rc2] `SHOW TAG KEYS FROM ...` returns ``use of closed network connection''

### ISSUE THREAD

**Issue by zstyblik** [influxdata/influxdb#5538]
Hello,

I've just noticed that `SHOW TAG KEYS FROM "measurement"` returns `Server returned error: write message type: use of closed network connection`. This does happen via Web UI/API and via CLI. I have tried pretty much everything, but I have no idea what's could possibly be wrong.
It seems to me only this command returns error. `SHOW TAG VALUES` works. InfluxDB itself seems to be working as well - data being written, CQs being executed, data points being returned. But `SHOW TAG KEYS FROM`? Nope.

InfluxDB v0.10.0-rc2 & TSM1.

**Comment by zstyblik** [comment]
This doesn't seem to work either:

```
SELECT mean(load1) FROM system WHERE time > now() - 30m GROUP BY time(1m), tags
```

but it should work, shouldn't it?

**Comment by seiflotfy** [comment]
Tried to replicate using a similar query

```sql
> SHOW TAG KEYS FROM "cpu"
name: cpu
---------
tagKey
host
region
```

```sql
SELECT mean(load) FROM cpu WHERE time > now() - 3m GROUP BY time(1m), host, region
name: cpu
tags: host=server01, region=uswest
time			mean
----			----
1454584980000000000	20.333333333333332
1454585040000000000	12
1454585100000000000	12.666666666666666
1454585160000000000	12
```

Am I missing something? I tried on both rc1 and git master :mag:  (could not find rc2 in the git tags)
The error message you are getting indicates that it might be something network related.

**Comment by zstyblik** [comment]
@seiflotfy thanks for trying out. The query you've posted, `SELECT mean(...`, works as well. The query I've posted was wrong. However, `SHOW TAG KEYS ...`, is still a no show. I've tried it even "locally" and I get the same error. If there is more I can do to debug it, I'm all ears :\

**Comment by zstyblik** [comment]
@seiflotfy I'm using rc2 from RPM.

**Comment by zstyblik** [comment]
```
influx -host X -port 8086
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://X:8086 version 0.10.0rc2
InfluxDB shell 0.10.0rc2
> USE telegraf
Using database telegraf
> SHOW TAG KEYS FROM "system"
ERR: write message type: use of closed network connection
```

**Comment by zstyblik** [comment]
RC2 tag @ https://github.com/influxdata/influxdb/tree/v0.10.0-rc2 ?

**Comment by seiflotfy** [comment]
Tried on RC2 still no luck :(
Can you provide me with the influxd output?

**Comment by zstyblik** [comment]
@seiflotfy log file is attached, although it went through some filtering process. Also, noteworthy is this not a clean RC2 instance and data have been around for a while. What comes to my mind is, may be there is a problem in `peers.json`, `node.js` or `raft.db`. Also, all those connection errors to localhost don't look healthy :\ Also, we've confirmed, as you did, this issue doesn't happen with clean RC2 instance. So it's probably some breaking change?

[influxdb01.txt](https://github.com/influxdata/influxdb/files/117358/influxdb01.txt)

**Comment by zstyblik** [comment]
Ok. Small update. It doesn't happen with newly created DB and metrics, but only with the DBs that have been around for a while. I hope this narrows it down a bit.

**Comment by zstyblik** [comment]
I mean, I had database with no measurements. So I've put some measurements there with Telegraf and `SHOW TAG KEYS` seems to be working there.

**Comment by seiflotfy** [comment]
Sweet, this narrows it down a bit. Do you recall at which version you started using influx. Maybe I can replicate it then by populating your initial version then upgrading a couple of times, then trying the request.

**Comment by zstyblik** [comment]
@seiflotfy the oldest version I have here is:

```
InfluxDB starting, version 0.10.0-nightly-614a37c, branch master, commit 614a37cdcd7a3fd674918144049e90899164894f, built 2016-01-07T05:00:48+0000
```

Unfortunately, I can't tell you exactly when this problem has occurred. We've also switched between nightly/beta/rc as was "needed". In other words, we were dodging issues.

I can try to spin up some older instances and try to restore data in backup and try with those. However, this might or might not work, because there were quite big changes to meta service and backup script. I think some of them are simply not backwards compatible or features are missing in older version.

node.json:
```
{"ID":2,"MetaServers":["localhost:8091"]}
```

Shouldn't there be ID:1?

peers.json
```
["localhost:8088"]
```

**Comment by seiflotfy** [comment]
I am not sure about the node.json part or the peers.json one (still finding myself around the code).
I will try later to run the same nightly populate it. Then I will try to upgrade to betas then rcs and try out the queries.
When upgrading were you backing up and restoring or just normal upgrade?

**Comment by zstyblik** [comment]
@seiflotfy actually, this probably won't go longer than 21.1. We had a working setup around that time. I mean, it was working.

>  When upgrading were you backing up and restoring or just normal upgrade?

As for upgrade, we are just rolling through. We don't do backup and restore.

**Comment by seiflotfy** [comment]
@zstyblik talking to @corylanou he suggested if you could try running
```sql
show servers
````
Can you paste the output here?

**Comment by zstyblik** [comment]
@seiflotfy sure.

```
> show servers
name: data_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8088  localhost:8088
2       localhost:8086  localhost:8088


name: meta_nodes
----------------
id      http_addr       tcp_addr
1       localhost:8091  localhost:8088
```

This isn't good, is it? :)

**Comment by zstyblik** [comment]
These do seem to be related to the issue:

```
[cluster] 2016/02/04 14:01:18 accept remote connection from 127.0.0.1:60216
[cluster] 2016/02/04 14:01:18 close remote connection from 127.0.0.1:60204
```

**Comment by seiflotfy** [comment]
Yeah so the problem here is you have 2 datanodes. Not sure this makes sense. You should be having one only AFAICT. right?

We are getting somewhere. :D
 
Let me see if by doing upgrades i will also get into having 2 datanodes.
Else it must be something to do with your config. Can you restart the service and make sure nothing is occupying ports 8088, 8089, 8086 ?

**Comment by zstyblik** [comment]
@seiflotfy that's correct. Actually, the reason I said it doesn't look right is, this issue is somewhat familiar. I'm not saying I've seen exactly the same issue, BUT it just sounds familiar to some issues I've seen before. I've already cycled instance couple times. I even spun up a new one with data restored from backup.
As for the configuration file, it should be in the output I've posted couple messages ago, if you want to check it out. But the only difference there are changes to directories. We have used `hostname=` before, though. It is no longer supported. Hmm. May be this has caused this issue?

Anyway. What would happen if I have removed `peers.json`, `node.json` and `raft.db`? I mean, this information about two nodes is stored somewhere. Also, changing node ID "manually", in the files, to 1 might fix the issue(?). I've seen it to be suggested somewhere.

**Comment by seiflotfy** [comment]
Lets try this step by step. First backup all three files. Then delete on and see if it works, if not the next, etc...
Tell me if it changes anything?

**Comment by zstyblik** [comment]
@seiflotfy will do :)

**Comment by seiflotfy** [comment]
Replicated the error.
Upgrading from beta1 to beta2 somehow messed up something.
```SQL
> SHOW SERVERS
name: data_nodes
----------------
id	http_addr	tcp_addr
2	localhost:8088	localhost:8088
3	localhost:8086	localhost:8088


name: meta_nodes
----------------
id	http_addr	tcp_addr
1	localhost:8091	localhost:8088
```

and 
```
> SHOW TAG KEYS FROM "cpu"
ERR: database name required
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

Will try to dig into it later!

**Comment by zstyblik** [comment]
@seiflotfy "cool" :)

**Comment by zstyblik** [comment]
Well, removing `raft.db` has fixed the issue. Downside is, everything is gone now. :) So that's really not a way to go.

**Comment by seiflotfy** [comment]
did you back it up?

**Comment by zstyblik** [comment]
Yeah, no worries. ;) I've spawned another instance with the data from backup and playing with it. Unfortunately, the server information is stored in `meta.00`, resp. `raft.db`. I don't know how to remove it. I'll try to restore from backup again. Turn the influxdb off and change ID to 1 in `node.json`. I'm not sure if that's going to help, though.

**Comment by rossmcdonald** [comment]
This looks like an upgrade issue that should have been resolved with 0.10.0-rc1. @zstyblik Was this server upgraded from 0.9?

Similar issues were seen with #5474. The solution for that ticket was to set the contents of your `node.json` file to `"ID":1`. I'd give that a shot, and let us know if the issues persist.

Oh and deleting `raft.db` will destroy the metastore, so I'd recommend against doing that in the future.

**Comment by zstyblik** [comment]
> Oh and deleting raft.db will destroy the metastore, so I'd recommend against doing that in the future.

Good to know! :)

> Was this server upgraded from 0.9?

@rossmcdonald no. Also:

> Upgrading from beta1 to beta2 somehow messed up something.

So I guess it wasn't resolved completely?

@seiflotfy setting ID to 1 didn't help. InfluxDB really insists on two servers and its `ID:2` :(

**Comment by rossmcdonald** [comment]
@zstyblik Thanks. I'll try to see if I can reproduce with the beta1 to beta2 upgrade path.

**Comment by seiflotfy** [comment]
@rossmcdonald AFAICT this happens when upgrading from beta1 to beta2
upgrading from beta1 to anything above does not trigger the issue, just between beta1 and beta2

**Comment by zstyblik** [comment]
May be a good question to ask is - is this reparable? If not, then I'd like to throw away the data at the main instance. Thanks.

**Comment by seiflotfy** [comment]
I think its repairable if we fiddle around with what is in the raft.db. I am not sure though will look in a bit.

**Comment by rossmcdonald** [comment]
@zstyblik This should be repairable as long as the `raft.db` is in tact. Regarding:

> setting ID to 1 didn't help. InfluxDB really insists on two servers and its ID:2 :(

Is it getting reset back to ID 2? Did you stop the service before you changed the ID? I've never seen it reset itself when manually changed.

**Comment by zstyblik** [comment]
@rossmcdonald no, but `SHOW SERVERS` still shows two nodes and the issue persists. Yes, the service has been stopped at that time.

**Comment by seiflotfy** [comment]
So after updating to master SHOW TAG KEYS FROM .... seems to work again
However still showing me the wrong 2 servers

**Comment by zstyblik** [comment]
Nope. I've tried it again, but it's no worky. :(

**Comment by jwilder** [comment]
`beta2` had an upgrade issue that could cause this.

**Comment by jwilder** [comment]
You should not see this if upgrading from `0.9` to `0.10`.

**Comment by zstyblik** [comment]
@jwilder it wasn't upgrade from 0.9.

**Comment by zstyblik** [comment]
If this issue is related only to beta1 and beta2, then I guess it can be closed.

**Comment by jwilder** [comment]
Closing since this is likely due to upgade issues that occurred with `beta2`.  If you see this in new installs of `0.10`, please re-open a new issue.

**Comment by 2008chny** [comment]
Hello @jwilder,



![6b3155dd-a536-43ff-bf2c-5429f8ad5c81](https://cloud.githubusercontent.com/assets/1881530/13068919/e8cb0dfe-d4ba-11e5-8874-ac793c15b441.png)
![1155cc0b-eb48-490a-b5b7-ef72e635e2c8](https://cloud.githubusercontent.com/assets/1881530/13068924/f1150f0a-d4ba-11e5-9707-1c86514abb93.png)
