### ISSUE TITLE
Issues with GDM during build

### ISSUE THREAD

**Issue by BGraco** [influxdata/influxdb#5774]
Trying to build master using the build.py script on a BeagleBone Black running Debian 7.

Originally I did not have GDM installed as I have not needed it in the past and did not re-check requirements, but it did look like the build script tried to handle it and failed.

```
Sun Feb 21 16:12:14 UTC 2016
Cloning into 'influxdb'...
remote: Counting objects: 51198, done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 51198 (delta 46), reused 0 (delta 0), pack-reused 51085
Receiving objects: 100% (51198/51198), 36.65 MiB | 2.12 MiB/s, done.
Resolving deltas: 100% (34821/34821), done.
# On branch master
nothing to commit (working directory clean)
Build Master!
Already up-to-date.

Checking environment:
- GOPATH -> /root/gocodez
- GOBIN -> None
- GOROOT -> /root/.gvm/gos/go1.4.3

Checking for dependencies:
- git -> /usr/bin/git
- go -> /root/.gvm/gos/go1.4.3/bin/go
- gdm -> ?
- gvm (optional) -> /root/.gvm/bin/gvm
- fpm (optional) -> ?
- rpmbuild (optional) -> ?

Downloading `gdm`...
Retrieving dependencies with `gdm`...


Invalid command!
-- Command run was: gdm restore
-- Failure was: [Errno 2] No such file or directory

Stopping.
```
Running go get github.com/sparrc/gdm did resolve the gdm dependency, but I still cannot get influx to build.
```
Sun Feb 21 16:20:22 UTC 2016
Cloning into 'influxdb'...
remote: Counting objects: 51198, done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 51198 (delta 46), reused 0 (delta 0), pack-reused 51085
Receiving objects: 100% (51198/51198), 36.65 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (34821/34821), done.
# On branch master
nothing to commit (working directory clean)
Build Master!
Already up-to-date.

Checking environment:
- GOPATH -> /root/gocodez
- GOBIN -> None
- GOROOT -> /root/.gvm/gos/go1.4.3

Checking for dependencies:
- git -> /usr/bin/git
- go -> /root/.gvm/gos/go1.4.3/bin/go
- gdm -> /root/.gvm/pkgsets/go1.4.3/global/bin/gdm
- gvm (optional) -> /root/.gvm/bin/gvm
- fpm (optional) -> ?
- rpmbuild (optional) -> ?

Retrieving dependencies with `gdm`...


Executed command failed!
-- Command run was: gdm restore
-- Failure was: ======= Go Dependency Manager =======
= working dir: /root/gocodez/src/github.com/influxdb/influxdb
= GOPATH:      /root/gocodez
=====================================
> Restoring /root/gocodez/src/collectd.org/api to 9fc824c70f713ea0f058a07b49a4c563ef2a3b98
> Restoring /root/gocodez/src/github.com/BurntSushi/toml to 5c4df71dfe9ac89ef6287afc05e4c1b16ae65a1e
> Restoring /root/gocodez/src/github.com/armon/go-metrics to 345426c77237ece5dab0e1605c3e4b35c3f54757
> Restoring /root/gocodez/src/github.com/bmizerany/pat to b8a35001b773c267eb260a691f4e5499a3531600
> Restoring /root/gocodez/src/github.com/boltdb/bolt to 2f846c3551b76d7710f159be840d66c3d064abbe
> Restoring /root/gocodez/src/github.com/davecgh/go-spew to fc32781af5e85e548d3f1abaf0fa3dbe8a72495c
> Restoring /root/gocodez/src/github.com/dgryski/go-bits to 86c69b3c986f9d40065df5bd8f765796549eef2e
> Restoring /root/gocodez/src/github.com/dgryski/go-bitstream to 27cd5973303fde7d914860be1ea4b927a6be0c92
> Restoring /root/gocodez/src/github.com/gogo/protobuf to 82d16f734d6d871204a3feb1a73cb220cc92574c
> Restoring /root/gocodez/src/github.com/golang/snappy to 5979233c5d6225d4a8e438cdd0b411888449ddab
> Restoring /root/gocodez/src/github.com/hashicorp/go-msgpack to fa3f63826f7c23912c15263591e65d54d080b458
> Restoring /root/gocodez/src/github.com/hashicorp/raft to 8fd9a2fdfd154f4b393aa24cff91e3c317efe839
> Restoring /root/gocodez/src/github.com/hashicorp/raft-boltdb to d1e82c1ec3f15ee991f7cc7ffd5b67ff6f5bbaee
> Restoring /root/gocodez/src/github.com/influxdata/usage-client to 475977e68d79883d9c8d67131c84e4241523f452
> Restoring /root/gocodez/src/github.com/jwilder/encoding to 07d88d4f35eec497617bee0c7bfe651a796dae13
> Restoring /root/gocodez/src/github.com/kimor79/gollectd to 61d0deeb4ffcc167b2a1baa8efd72365692811bc
> Restoring /root/gocodez/src/github.com/paulbellamy/ratecounter to 5a11f585a31379765c190c033b6ad39956584447
> Restoring /root/gocodez/src/github.com/peterh/liner to ad1edfd30321d8f006ccf05f1e0524adeb943060
> Restoring /root/gocodez/src/github.com/rakyll/statik to 274df120e9065bdd08eb1120e0375e3dc1ae8465
> Restoring /root/gocodez/src/golang.org/x/crypto to 1f22c0103821b9390939b6776727195525381532
> Restoring /root/gocodez/src/gopkg.in/fatih/pool.v2 to cba550ebf9bce999a02e963296d4bc7a486cb715
# cd .; git clone https://go.googlesource.com/crypto /root/gocodez/src/golang.org/x/crypto
Cloning into '/root/gocodez/src/golang.org/x/crypto'...
error: gnutls_handshake() failed: A TLS packet with unexpected length was received. while accessing https://go.googlesource.com/crypto/info/refs
fatal: HTTP request failed

ERROR restoring some imports:
-   Error creating repo at /root/gocodez/src/golang.org/x/crypto, exit status 128


Stopping.
```

**Comment by rossmcdonald** [comment]
@BGraco Are you still receiving the last error consistently?

```
Error creating repo at /root/gocodez/src/golang.org/x/crypto, exit status 128
```

I have seen intermittent issues with some of the Go repositories (specifically the crypto library), but it seems to resolve itself after a couple tries.

I will also be adding a fix for the first issue you encountered with `gdm` later today.

**Comment by BGraco** [comment]
As suggested, I tried to build influxdb multiple times. On the seventh try it worked!

Then I hit this error...
```
Executed command failed!
-- Command run was: GOOS=linux GOARCH=arm GOARM=6 go build -o build/influx_stress -ldflags="-X main.buildTime='2016-02-23T23:22:01.921608' -X main.version=v0.10.0 -X main.branch=master -X main.commit=e32e5ff481c63f75d8f8bfe3f55dfc7a23559cf0" ./cmd/influx_stress/influx_stress.go
-- Failure was: cmd/influx_stress/influx_stress.go:9:2: cannot find package "github.com/influxdata/influxdb/stress" in any of:
	/root/.gvm/gos/go1.6/src/github.com/influxdata/influxdb/stress (from $GOROOT)
	/root/gocodez/src/github.com/influxdata/influxdb/stress (from $GOPATH)


Stopping.
```

If I retried the build without cleaning the gocodez dir I got the following error
```
Checking environment:
- GOPATH -> /root/gocodez
- GOBIN -> None
- GOROOT -> /root/.gvm/gos/go1.4.3

Checking for dependencies:
- git -> /usr/bin/git
- go -> /root/.gvm/gos/go1.4.3/bin/go
- gdm -> /root/.gvm/pkgsets/go1.4.3/global/bin/gdm
- gvm (optional) -> /root/.gvm/bin/gvm
- fpm (optional) -> ?
- rpmbuild (optional) -> ?

Retrieving dependencies with `gdm`...


Executed command failed!
-- Command run was: gdm restore
-- Failure was: ======= Go Dependency Manager =======
= working dir: /root/gocodez/src/github.com/influxdb/influxdb
= GOPATH:      /root/gocodez
=====================================
> Restoring /root/gocodez/src/collectd.org/api to 9fc824c70f713ea0f058a07b49a4c563ef2a3b98
> Restoring /root/gocodez/src/github.com/BurntSushi/toml to 5c4df71dfe9ac89ef6287afc05e4c1b16ae65a1e
> Restoring /root/gocodez/src/github.com/armon/go-metrics to 345426c77237ece5dab0e1605c3e4b35c3f54757
> Restoring /root/gocodez/src/github.com/bmizerany/pat to b8a35001b773c267eb260a691f4e5499a3531600
> Restoring /root/gocodez/src/github.com/boltdb/bolt to 2f846c3551b76d7710f159be840d66c3d064abbe
> Restoring /root/gocodez/src/github.com/davecgh/go-spew to fc32781af5e85e548d3f1abaf0fa3dbe8a72495c
> Restoring /root/gocodez/src/github.com/dgryski/go-bits to 86c69b3c986f9d40065df5bd8f765796549eef2e
> Restoring /root/gocodez/src/github.com/dgryski/go-bitstream to 27cd5973303fde7d914860be1ea4b927a6be0c92
> Restoring /root/gocodez/src/github.com/gogo/protobuf to 82d16f734d6d871204a3feb1a73cb220cc92574c
> Restoring /root/gocodez/src/github.com/golang/snappy to 5979233c5d6225d4a8e438cdd0b411888449ddab
> Restoring /root/gocodez/src/github.com/hashicorp/go-msgpack to fa3f63826f7c23912c15263591e65d54d080b458
> Restoring /root/gocodez/src/github.com/hashicorp/raft to 8fd9a2fdfd154f4b393aa24cff91e3c317efe839
> Restoring /root/gocodez/src/github.com/hashicorp/raft-boltdb to d1e82c1ec3f15ee991f7cc7ffd5b67ff6f5bbaee
> Restoring /root/gocodez/src/github.com/influxdata/usage-client to 475977e68d79883d9c8d67131c84e4241523f452
> Restoring /root/gocodez/src/github.com/jwilder/encoding to 07d88d4f35eec497617bee0c7bfe651a796dae13
> Restoring /root/gocodez/src/github.com/kimor79/gollectd to 61d0deeb4ffcc167b2a1baa8efd72365692811bc
> Restoring /root/gocodez/src/github.com/paulbellamy/ratecounter to 5a11f585a31379765c190c033b6ad39956584447
> Restoring /root/gocodez/src/github.com/peterh/liner to ad1edfd30321d8f006ccf05f1e0524adeb943060
> Restoring /root/gocodez/src/github.com/rakyll/statik to 274df120e9065bdd08eb1120e0375e3dc1ae8465
> Restoring /root/gocodez/src/golang.org/x/crypto to 1f22c0103821b9390939b6776727195525381532
> Restoring /root/gocodez/src/gopkg.in/fatih/pool.v2 to cba550ebf9bce999a02e963296d4bc7a486cb715
# cd /root/gocodez/src/golang.org/x/crypto; git pull --ff-only
error: The requested URL returned error: 406 while accessing https://go.googlesource.com/crypto/info/refs
fatal: HTTP request failed

ERROR restoring some imports:
-   Error downloading changes to /root/gocodez/src/golang.org/x/crypto, exit status 1


Stopping.
```

I am going to spam retry with go1.4.3 and see if that makes any difference. Otherwise I will just rollback the build.py file to avoid gdm.

**Comment by rossmcdonald** [comment]
@BGraco Sorry for the issues. `gdm` was added so that we can get some reproducibility in our builds, instead of just building from master for each of the imported projects. I've never seen that many issues pulling packages though.

@sparrc Have you seen anything like the issue above before with `gdm`?

**Comment by rossmcdonald** [comment]
@BGraco Also, I'm going to be merging a few changes to `build.py` with [this](https://github.com/influxdata/influxdb/pull/5596) PR that should fix the first issue you encountered. In addition, there are a few other updates around the handling of ARM architectures included in that PR that I'd love to have your feedback on (particularly [here](https://github.com/influxdata/influxdb/pull/5596/files#diff-2955d5257f635de1df53f55a171ca5c7R407) and [here](https://github.com/influxdata/influxdb/pull/5596/files#diff-2955d5257f635de1df53f55a171ca5c7R97)), though we're still using `gdm` for version management. 

We're also going to be offering ARM (armhf, armel, and arm64) builds through the repos.influxdata.com repository by the next release so you won't have to continually rebuild from source (unless you really want to).

**Comment by sparrc** [comment]
it looks like it's an issue with the crypto libraries hosting. The commented line at the end is all it's trying to do, and the git pull is getting a 406 error.

```
# cd /root/gocodez/src/golang.org/x/crypto; git pull --ff-only
error: The requested URL returned error: 406 while accessing https://go.googlesource.com/crypto/info/refs
```

**Comment by BGraco** [comment]
Just tried the latest. It seems the issue with gdm not getting properly downloaded/installed is resolved, but crypto still fails every time. Weird things is, if I manually run the shown commands I have no issues....
```
root@influxb:~/gocodez/src/github.com/influxdata/influxdb# ./build.py 

Checking environment:
- GOPATH -> /root/gocodez
- GOBIN -> None
- GOROOT -> /root/.gvm/gos/go1.5.3

Checking for dependencies:
- git -> /usr/bin/git
- go -> /root/.gvm/gos/go1.5.3/bin/go
- gdm -> ?
- gvm (optional) -> /root/.gvm/bin/gvm
- fpm (optional) -> ?
- rpmbuild (optional) -> ?

Downloading `gdm`...
Retrieving dependencies with `gdm`...


Executed command failed!
-- Command run was: /root/gocodez/bin/gdm restore
-- Failure was: ======= Go Dependency Manager =======
= working dir: /root/gocodez/src/github.com/influxdata/influxdb
= GOPATH:      /root/gocodez
=====================================
> Restoring /root/gocodez/src/collectd.org to 9fc824c70f713ea0f058a07b49a4c563ef2a3b98
> Restoring /root/gocodez/src/github.com/BurntSushi/toml to a4eecd407cf4129fc902ece859a0114e4cf1a7f4
> Restoring /root/gocodez/src/github.com/armon/go-metrics to 345426c77237ece5dab0e1605c3e4b35c3f54757
> Restoring /root/gocodez/src/github.com/bmizerany/pat to b8a35001b773c267eb260a691f4e5499a3531600
> Restoring /root/gocodez/src/github.com/boltdb/bolt to 2f846c3551b76d7710f159be840d66c3d064abbe
> Restoring /root/gocodez/src/github.com/davecgh/go-spew to fc32781af5e85e548d3f1abaf0fa3dbe8a72495c
> Restoring /root/gocodez/src/github.com/dgryski/go-bits to 86c69b3c986f9d40065df5bd8f765796549eef2e
> Restoring /root/gocodez/src/github.com/dgryski/go-bitstream to 27cd5973303fde7d914860be1ea4b927a6be0c92
> Restoring /root/gocodez/src/github.com/gogo/protobuf to 82d16f734d6d871204a3feb1a73cb220cc92574c
> Restoring /root/gocodez/src/github.com/golang/snappy to 5979233c5d6225d4a8e438cdd0b411888449ddab
> Restoring /root/gocodez/src/github.com/hashicorp/go-msgpack to fa3f63826f7c23912c15263591e65d54d080b458
> Restoring /root/gocodez/src/github.com/hashicorp/raft to 8fd9a2fdfd154f4b393aa24cff91e3c317efe839
> Restoring /root/gocodez/src/github.com/hashicorp/raft-boltdb to d1e82c1ec3f15ee991f7cc7ffd5b67ff6f5bbaee
> Restoring /root/gocodez/src/github.com/influxdata/usage-client to 475977e68d79883d9c8d67131c84e4241523f452
> Restoring /root/gocodez/src/github.com/jwilder/encoding to 07d88d4f35eec497617bee0c7bfe651a796dae13
> Restoring /root/gocodez/src/github.com/kimor79/gollectd to 61d0deeb4ffcc167b2a1baa8efd72365692811bc
> Restoring /root/gocodez/src/github.com/paulbellamy/ratecounter to 5a11f585a31379765c190c033b6ad39956584447
> Restoring /root/gocodez/src/github.com/peterh/liner to ad1edfd30321d8f006ccf05f1e0524adeb943060
> Restoring /root/gocodez/src/github.com/rakyll/statik to 274df120e9065bdd08eb1120e0375e3dc1ae8465
> Restoring /root/gocodez/src/golang.org/x/crypto to 1f22c0103821b9390939b6776727195525381532
> Restoring /root/gocodez/src/gopkg.in/fatih/pool.v2 to cba550ebf9bce999a02e963296d4bc7a486cb715
# cd .; git clone https://go.googlesource.com/crypto /root/gocodez/src/golang.org/x/crypto
Cloning into '/root/gocodez/src/golang.org/x/crypto'...
error: gnutls_handshake() failed: A TLS packet with unexpected length was received. while accessing https://go.googlesource.com/crypto/info/refs
fatal: HTTP request failed

ERROR restoring some imports:
-   Error creating repo at /root/gocodez/src/golang.org/x/crypto, exit status 128


Stopping.
root@influxb:~/gocodez/src/github.com/influxdata/influxdb# git clone https://go.googlesource.com/crypto /root/gocodez/src/golang.org/x/crypto
Cloning into '/root/gocodez/src/golang.org/x/crypto'...
remote: Total 2199 (delta 1425), reused 2199 (delta 1425)
Receiving objects: 100% (2199/2199), 1.46 MiB | 1.83 MiB/s, done.
Resolving deltas: 100% (1425/1425), done.
root@influxb:~/gocodez/src/github.com/influxdata/influxdb# ./build.py 

Checking environment:
- GOPATH -> /root/gocodez
- GOBIN -> None
- GOROOT -> /root/.gvm/gos/go1.5.3

Checking for dependencies:
- git -> /usr/bin/git
- go -> /root/.gvm/gos/go1.5.3/bin/go
- gdm -> ?
- gvm (optional) -> /root/.gvm/bin/gvm
- fpm (optional) -> ?
- rpmbuild (optional) -> ?

Downloading `gdm`...
Retrieving dependencies with `gdm`...


Executed command failed!
-- Command run was: /root/gocodez/bin/gdm restore
-- Failure was: ======= Go Dependency Manager =======
= working dir: /root/gocodez/src/github.com/influxdata/influxdb
= GOPATH:      /root/gocodez
=====================================
> Restoring /root/gocodez/src/collectd.org to 9fc824c70f713ea0f058a07b49a4c563ef2a3b98
> Restoring /root/gocodez/src/github.com/BurntSushi/toml to a4eecd407cf4129fc902ece859a0114e4cf1a7f4
> Restoring /root/gocodez/src/github.com/armon/go-metrics to 345426c77237ece5dab0e1605c3e4b35c3f54757
> Restoring /root/gocodez/src/github.com/bmizerany/pat to b8a35001b773c267eb260a691f4e5499a3531600
> Restoring /root/gocodez/src/github.com/boltdb/bolt to 2f846c3551b76d7710f159be840d66c3d064abbe
> Restoring /root/gocodez/src/github.com/davecgh/go-spew to fc32781af5e85e548d3f1abaf0fa3dbe8a72495c
> Restoring /root/gocodez/src/github.com/dgryski/go-bits to 86c69b3c986f9d40065df5bd8f765796549eef2e
> Restoring /root/gocodez/src/github.com/dgryski/go-bitstream to 27cd5973303fde7d914860be1ea4b927a6be0c92
> Restoring /root/gocodez/src/github.com/gogo/protobuf to 82d16f734d6d871204a3feb1a73cb220cc92574c
> Restoring /root/gocodez/src/github.com/golang/snappy to 5979233c5d6225d4a8e438cdd0b411888449ddab
> Restoring /root/gocodez/src/github.com/hashicorp/go-msgpack to fa3f63826f7c23912c15263591e65d54d080b458
> Restoring /root/gocodez/src/github.com/hashicorp/raft to 8fd9a2fdfd154f4b393aa24cff91e3c317efe839
> Restoring /root/gocodez/src/github.com/hashicorp/raft-boltdb to d1e82c1ec3f15ee991f7cc7ffd5b67ff6f5bbaee
> Restoring /root/gocodez/src/github.com/influxdata/usage-client to 475977e68d79883d9c8d67131c84e4241523f452
> Restoring /root/gocodez/src/github.com/jwilder/encoding to 07d88d4f35eec497617bee0c7bfe651a796dae13
> Restoring /root/gocodez/src/github.com/kimor79/gollectd to 61d0deeb4ffcc167b2a1baa8efd72365692811bc
> Restoring /root/gocodez/src/github.com/paulbellamy/ratecounter to 5a11f585a31379765c190c033b6ad39956584447
> Restoring /root/gocodez/src/github.com/peterh/liner to ad1edfd30321d8f006ccf05f1e0524adeb943060
> Restoring /root/gocodez/src/github.com/rakyll/statik to 274df120e9065bdd08eb1120e0375e3dc1ae8465
> Restoring /root/gocodez/src/golang.org/x/crypto to 1f22c0103821b9390939b6776727195525381532
> Restoring /root/gocodez/src/gopkg.in/fatih/pool.v2 to cba550ebf9bce999a02e963296d4bc7a486cb715
# cd /root/gocodez/src/golang.org/x/crypto; git pull --ff-only
error: The requested URL returned error: 406 while accessing https://go.googlesource.com/crypto/info/refs
fatal: HTTP request failed

ERROR restoring some imports:
-   Error downloading changes to /root/gocodez/src/golang.org/x/crypto, exit status 1


Stopping.
root@influxb:~/gocodez/src/github.com/influxdata/influxdb# cd /root/gocodez/src/golang.org/x/crypto;
root@influxb:~/gocodez/src/golang.org/x/crypto# git pull --ff-only

Already up-to-date.
root@influxb:~/gocodez/src/golang.org/x/crypto# 
```

**Comment by sparrc** [comment]
can you run `cd /root/gocodez/src/golang.org/x/crypto && git remote show origin`?

mine looks like this:

```
% git remote show origin
* remote origin
  Fetch URL: https://go.googlesource.com/crypto
  Push  URL: https://go.googlesource.com/crypto
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master rebases onto remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

**Comment by BGraco** [comment]
```
root@influxb:~/gocodez/src/golang.org/x/crypto# cd /root/gocodez/src/golang.org/x/crypto && git remote show origin
* remote origin
  Fetch URL: https://go.googlesource.com/crypto
  Push  URL: https://go.googlesource.com/crypto
  HEAD branch: master
  Remote branch:
    master tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date)
```

**Comment by BGraco** [comment]
Updating now that 0.11 rc is released, still seem to be stuck....
```
root@influxb:~# mkdir $HOME/gocodez
root@influxb:~# export GOPATH=$HOME/gocodez
root@influxb:~# go get github.com/influxdata/influxdb
root@influxb:~# cd $GOPATH/src/github.com/influxdata/influxdb
root@influxb:~/gocodez/src/github.com/influxdata/influxdb# gdm restore
======= Go Dependency Manager =======
= working dir: /root/gocodez/src/github.com/influxdata/influxdb
= GOPATH:      /root/gocodez
=====================================
> Restoring /root/gocodez/src/collectd.org to 9fc824c70f713ea0f058a07b49a4c563ef2a3b98
> Restoring /root/gocodez/src/github.com/BurntSushi/toml to a4eecd407cf4129fc902ece859a0114e4cf1a7f4
> Restoring /root/gocodez/src/github.com/armon/go-metrics to 345426c77237ece5dab0e1605c3e4b35c3f54757
> Restoring /root/gocodez/src/github.com/bmizerany/pat to b8a35001b773c267eb260a691f4e5499a3531600
> Restoring /root/gocodez/src/github.com/boltdb/bolt to 2f846c3551b76d7710f159be840d66c3d064abbe
> Restoring /root/gocodez/src/github.com/davecgh/go-spew to fc32781af5e85e548d3f1abaf0fa3dbe8a72495c
> Restoring /root/gocodez/src/github.com/dgryski/go-bits to 86c69b3c986f9d40065df5bd8f765796549eef2e
> Restoring /root/gocodez/src/github.com/dgryski/go-bitstream to 27cd5973303fde7d914860be1ea4b927a6be0c92
> Restoring /root/gocodez/src/github.com/gogo/protobuf to 82d16f734d6d871204a3feb1a73cb220cc92574c
> Restoring /root/gocodez/src/github.com/golang/snappy to 5979233c5d6225d4a8e438cdd0b411888449ddab
> Restoring /root/gocodez/src/github.com/hashicorp/go-msgpack to fa3f63826f7c23912c15263591e65d54d080b458
> Restoring /root/gocodez/src/github.com/hashicorp/raft to 8fd9a2fdfd154f4b393aa24cff91e3c317efe839
> Restoring /root/gocodez/src/github.com/hashicorp/raft-boltdb to d1e82c1ec3f15ee991f7cc7ffd5b67ff6f5bbaee
> Restoring /root/gocodez/src/github.com/influxdata/usage-client to 475977e68d79883d9c8d67131c84e4241523f452
> Restoring /root/gocodez/src/github.com/jwilder/encoding to 07d88d4f35eec497617bee0c7bfe651a796dae13
> Restoring /root/gocodez/src/github.com/kimor79/gollectd to 61d0deeb4ffcc167b2a1baa8efd72365692811bc
> Restoring /root/gocodez/src/github.com/paulbellamy/ratecounter to 5a11f585a31379765c190c033b6ad39956584447
> Restoring /root/gocodez/src/github.com/peterh/liner to ad1edfd30321d8f006ccf05f1e0524adeb943060
> Restoring /root/gocodez/src/github.com/rakyll/statik to 274df120e9065bdd08eb1120e0375e3dc1ae8465
> Restoring /root/gocodez/src/golang.org/x/crypto to 1f22c0103821b9390939b6776727195525381532
> Restoring /root/gocodez/src/golang.org/x/tools to 8b178a93c1f5b5c8f4e36cd6bd64e0d5bf0ee180
> Restoring /root/gocodez/src/gopkg.in/fatih/pool.v2 to cba550ebf9bce999a02e963296d4bc7a486cb715
# cd .; git clone https://go.googlesource.com/crypto /root/gocodez/src/golang.org/x/crypto
Cloning into '/root/gocodez/src/golang.org/x/crypto'...
error: gnutls_handshake() failed: A TLS packet with unexpected length was received. while accessing https://go.googlesource.com/crypto/info/refs
fatal: HTTP request failed
# cd .; git clone https://go.googlesource.com/tools /root/gocodez/src/golang.org/x/tools
Cloning into '/root/gocodez/src/golang.org/x/tools'...
error: gnutls_handshake() failed: A TLS packet with unexpected length was received. while accessing https://go.googlesource.com/tools/info/refs
fatal: HTTP request failed

ERROR restoring some imports:
-   Error creating repo at /root/gocodez/src/golang.org/x/crypto, exit status 128
-   Error creating repo at /root/gocodez/src/golang.org/x/tools, exit status 128
```

**Comment by sparrc** [comment]
Sorry @BGraco, but this isn't an issue that InfluxDB can solve for you, it appears to be a problem with your proxy & git/gnutls. From the error output, you are getting an error running git clone from the `gnutls_handshake()` function.

I searched around for that error message and found this http://askubuntu.com/questions/186847/error-gnutls-handshake-failed-when-connecting-to-https-servers & http://stackoverflow.com/questions/29245292/how-can-i-make-git-tell-curl-to-use-openssl-instead-of-gnutls-without-rebuilding, which both appear to solve the issue by compiling git with openssl instead of gnutls.

The other option is to simply change your local build.py script to skip the gdm command, but this won't get you the reproducible builds that it's there for.

**Comment by BGraco** [comment]
This is a post to confirm that compiling git with openssl instead of gnutls did resolved my issue.

Thanks for the help!

**Comment by sparrc** [comment]
glad to hear that worked for you, thanks @BGraco!
