### ISSUE TITLE
ubuntu 16 apt-get installing influxdb 0.10.0 instead of latest

### ISSUE THREAD

**Issue by boynet** [influxdata/influxdb#6773]
### Bug report

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]
Ubuntu 16.04 LTS Profile (Latest 64 bit (4.5.5-x86_64-linode69))

__Steps to reproduce:__

1. [First Step]
just copy pasting from this guide:https://docs.influxdata.com/influxdb/v0.13/introduction/installation/
```
(curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list)

sudo apt-get update && sudo apt-get install influxdb
sudo service influxdb start

```

after running I am getting this message:
```

2016/06/02 14:57:19 InfluxDB starting, version 0.10.0, branch unknown, commit unknown, built unknown
2016/06/02 14:57:19 Go version go1.6rc1, GOMAXPROCS set to 1
2016/06/02 14:57:19 no configuration provided, using default settings
run: open server: listen: listen tcp :8088: bind: address already in use

```

I can successfully install by manually download from download page but then `service influxd` return `influxd: unrecognized service`.

tried a couple method of getting the influxd command to act like service but cant get it right

**Comment by rossmcdonald** [comment]
@boynet Can you provide the output to the following commands?

```
influxd version
dpkg -l influxdb
```

I just ran through a test installation, but didn't see any issues. Also the build that you're running looks to have been compiled manually using Go 1.6rc1 (which isn't what the `0.10` branch was built with).

**Comment by boynet** [comment]
```
influxd version
InfluxDB v0.10.0 (git: unknown unknown, built unknown)
```

```
dpkg -l influxdb
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  influxdb                                              0.10.0+dfsg1-1                  amd64                           Scalable datastore for metrics, events, and real-time analytics
root@ubuntu:/etc/init.d#
```

this should be 3 separate commands or 1 line?
```
$curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
$source /etc/lsb-release
$echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
```

**Comment by rossmcdonald** [comment]
Regarding:

> this should be 3 separate commands or 1 line?

Those are three distinct commands. And where did you get the original `0.10.0+dfsg1-1` release? That's not one of our packages, so I'm not sure what the upgrade path will look like.

**Comment by boynet** [comment]
I can give you ssh access to the terminal\record a video of my steps, I just create new linode with ubuntu 16, follow the guide steps and that what I got didn't do anything special

**Comment by boynet** [comment]
here is the video(just copy pasting nothing special):
https://www.youtube.com/watch?v=EKyVxMyOnfo&feature=youtu.be

**Comment by rmarchei** [comment]
It looks like there's an issue on the Packages file:

Ubuntu 16.04: https://repos.influxdata.com/ubuntu/dists/xenial/stable/binary-amd64/Packages
Ubuntu 14.04: https://repos.influxdata.com/ubuntu/dists/trusty/stable/binary-amd64/Packages

**Comment by rossmcdonald** [comment]
@rmarchei Ah, thanks! For some reason the xenial repo was having issues. They should now be resolved, though.

@boynet Can you run an `apt-get update` and then try re-installing? It seems the `dfsg` one is a Debian package, but I'm not sure how that go installed instead.

**Comment by rmarchei** [comment]
Thanks to you @rossmcdonald, influxdb works now, but on the Packages file chronograf is still missing

**Comment by rossmcdonald** [comment]
@rmarchei That should now be fixed as well. Sorry about that!

**Comment by rossmcdonald** [comment]
@boynet Since the repo has been fixed, I'm going to go ahead and close out this issue. Please feel free respond here if you continue to see issues, though.

**Comment by boynet** [comment]
@rossmcdonald thanks I am getting version 0.13.0 now, but still service influxdb return "unrecognized service" 

I think they did some changes in the services area

**Comment by rossmcdonald** [comment]
@boynet What do you get if you run a `/etc/init.d/influxdb start`?

**Comment by boynet** [comment]
-bash: /etc/init.d/influxdb: No such file or directory

**Comment by rossmcdonald** [comment]
@boynet Ah, sorry, I'm a little new to systemd. The command should be `systemctl status influxdb`. Does that return anything?

**Comment by boynet** [comment]
yap this:

```
root@ubuntu:/etc/init# systemctl status influxdb
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2016-06-03 04:34:55 UTC; 10h ago
     Docs: https://docs.influxdata.com/influxdb/
 Main PID: 4068 (sh)
    Tasks: 8 (limit: 512)
   CGroup: /system.slice/influxdb.service
           ├─4068 /bin/sh -c /usr/bin/influxd -config /etc/influxdb/influxdb.conf  >>/dev/null 2>>/var/log/influxdb/influxd.log
           └─4073 /usr/bin/influxd -config /etc/influxdb/influxdb.conf

Jun 03 04:34:55 ubuntu systemd[1]: Started InfluxDB is an open-source, distributed, time series database.

```

**Comment by rossmcdonald** [comment]
Okay, great. It looks like it's running properly then. You should be able to see the latest log details in `/var/log/influxdb/influxd.log`.

Instead of using the `service` command, use `systemctl start|stop|restart|status influxdb`.

**Comment by boynet** [comment]
oh yes, thank you :)
maybe add something to the docs? about 
`systemctl enable influxdb`

**Comment by scriptfans** [comment]
On my arm64 ubuntu 16.04, This problem still exists, please fix it, thanks!

**Comment by scriptfans** [comment]
The index file is empty:

https://repos.influxdata.com/ubuntu/dists/xenial/stable/binary-arm64/Packages

**Comment by sLuvpreet33** [comment]
Fellas I am facing this same issue, and  
my `systemctl status influxdb` returns this,

`luvpreet@DHARI-Inspiron-3542:/$ systemctl status influxdb`
`● influxdb.service - InfluxDB is an open-source, distributed, time series database`
`   Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)`
   `Active: inactive (dead) (Result: exit-code) since Sat 2017-03-18 23:39:14 IST; 1 day 2h ago`
     `Docs: https://docs.influxdata.com/influxdb/`
 `Main PID: 5119 (code=exited, status=1/FAILURE)`

`Mar 18 23:39:13 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Unit entered failed state.`
`Mar 18 23:39:13 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Failed with result 'exit-code'.`
`Mar 18 23:39:14 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Service hold-off time over, scheduling restart.`
`Mar 18 23:39:14 DHARI-Inspiron-3542 systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.`
`Mar 18 23:39:14 DHARI-Inspiron-3542 systemd[1]: influxdb.service: Start request repeated too quickly.`
`Mar 18 23:39:14 DHARI-Inspiron-3542 systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.`


Its getting very frustrated now, please look at it.

**Comment by sLuvpreet33** [comment]
Here is the output of `journalctl -xe`

https://bpaste.net/show/76fb55e368d4

influx CLI is working if I run `influx` on terminal. 

Have a look at it, I will be thankful to you if you solve this problem.

**Comment by rossmcdonald** [comment]
@sLuvpreet33 Your error has nothing to do with this issue. From your logs:

```
Mar 20 01:44:19 DHARI-Inspiron-3542 influxd[10551]: run: open server: listen: listen tcp :8088: bind: address already in use
```

Something is already listening on port 8088. Based on your comment:

> influx CLI is working if I run influx on terminal.

It sounds like InfluxDB is already running if the `influx` CLI command works, so it's probably running outside of systemd. Try stopping/killing it, and then restart the process with `systemctl start influxdb`.

**Comment by sLuvpreet33** [comment]
I tried literally everything, looks like there was some issue with this
version of influxdb.

I installed an older version, and it worked very smoothly.
Grazie.
