### ISSUE TITLE
Influx shell: if there is an error parsing a JSON response, the shell does not show the actual body of the response

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/influxdb#6856]
When the Influx shell sees a JSON parsing error (which should never happen and is therefore indicative of a bug on the server), the shell only displays the parsing error and does not display the actual body of the response.

As seen in #6846:
```
> select non_negative_derivative(value) from snmp_rx where host='xxx' and type_instance='272662528' and time > now() - 10m
ERR: invalid character 'j' looking for beginning of value
```

The actual error message from the server might look like:

>  json: error calling MarshalJSON for type httpd.Response: json: error calling MarshalJSON for type *influxql.Result: json: unsupported value: NaN

Showing the full error message in the shell will help troubleshooting go more smoothly.

**Comment by e-dard** [comment]
@mark-rushakoff is this serendipitously fixed via https://github.com/influxdata/influxdb/pull/6565?

**Comment by mark-rushakoff** [comment]
@e-dard: Not fixed. I just tried on master as of bed66cfbe, with code added on the server to intentionally return non-JSON, and the client still does not print out the response body.

```
> select * from hello
ERR: invalid character '\x1f' looking for beginning of value
> exit

$ curl localhost:8086/query?q=hello
HELLO!
```

**Comment by jsternberg** [comment]
Fixed via #7280. It will be merged into the master branch after we release 1.0.1.
