### ISSUE TITLE
InfluxDB 1.2.4 leaving .tsm.tmp files, consuming all disk

### ISSUE THREAD

**Issue by forsberg** [influxdata/influxdb#8526]
### Bug report

I seem to be hitting #7712, although with InfluxDB 1.2.4. So opening new issue as requested.

__System info:__ [Include InfluxDB version, operating system name, and other relevant details]

* InfluxDB 1.2.4-1
* Linux ospmon01 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
* Debian GNU/Linux 8.8 (jessie) 
* 12 cores (24 HTs), 48G of memory

__Steps to reproduce:__

1. Start InfluxDB
2. Wait a week. 
3. Have a look at available disk. It has decreased significantly.
4. Restart InfluxDB. Disk size decreases significantly.

Attaching debug info (note: If I try to do the curl provided as example, I just get back "no such profile all") as well as output of 'find /var/lib/influxdb'. 

[influxdb-debug.ospmon01.1498462213.tar.gz](https://github.com/influxdata/influxdb/files/1101430/influxdb-debug.ospmon01.1498462213.tar.gz)
[var-lib-influxdb-files.txt](https://github.com/influxdata/influxdb/files/1101444/var-lib-influxdb-files.txt)

**Comment by jwilder** [comment]
This should be fixed in the latest nightlies/1.3.0.

**Comment by jwilder** [comment]
Fixed via #8416

**Comment by forsberg** [comment]
Thankyou for quick reply with positive news! :-)

**Comment by forsberg** [comment]
Not so sure this problem is gone with snapshot (1.4.0~n20170626). Still see a lot of .tsm.tmp files.
`
root@ospmon01:/var/lib/influxdb/data/telegraf/default# ls -l */*.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  453432498 jun 27 07:48 2820/000000401-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89962537 jun 27 07:52 2820/000000405-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91374007 jun 27 07:57 2820/000000409-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80926595 jun 27 07:59 2820/000000411-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74192767 jun 27 08:00 2820/000000412-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  671120891 jun 27 08:45 2820/000000449-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   93520693 jun 27 08:48 2820/000000453-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91030568 jun 27 08:53 2820/000000457-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90520293 jun 27 08:57 2820/000000461-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80122214 jun 27 09:00 2820/000000463-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   75825584 jun 27 09:01 2820/000000464-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 2147809164 jun 27 09:07 2820/000000465-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   21420453 jun 27 09:07 2820/000000465-000000007.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  265336446 jun 27 09:59 2820/000000513-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80049928 jun 27 10:00 2820/000000515-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  449570736 jun 27 10:55 2820/000000561-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92099207 jun 27 10:59 2820/000000565-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74662593 jun 27 11:00 2820/000000566-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  662455502 jun 27 11:51 2820/000000609-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92675700 jun 27 11:55 2820/000000613-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91718588 jun 27 11:59 2820/000000617-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74944286 jun 27 12:00 2820/000000618-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  882485409 jun 27 12:48 2820/000000657-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   95345940 jun 27 12:51 2820/000000661-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92707624 jun 27 12:55 2820/000000665-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91991956 jun 27 13:00 2820/000000669-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1111840640 jun 27 13:44 2820/000000705-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   96368239 jun 27 13:47 2820/000000709-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   94464828 jun 27 13:51 2820/000000713-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92516185 jun 27 13:56 2820/000000717-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   93019899 jun 27 14:01 2820/000000721-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  369815815 jun 27 14:57 2820/000000769-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   81614896 jun 27 14:59 2820/000000771-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74912548 jun 27 15:00 2820/000000772-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1636754244 jun 27 15:56 2820/000000817-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92329892 jun 27 15:57 2820/000000821-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   82218473 jun 27 16:00 2820/000000823-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   77109858 jun 27 16:01 2820/000000824-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  297438493 jun 27 16:49 2820/000000865-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90387300 jun 27 16:53 2820/000000869-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90203444 jun 27 16:58 2820/000000873-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80714127 jun 27 17:00 2820/000000875-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  488465100 jun 27 17:46 2820/000000913-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   95393305 jun 27 17:49 2820/000000917-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92385931 jun 27 17:54 2820/000000921-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92195950 jun 27 17:59 2820/000000925-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74487471 jun 27 18:00 2820/000000926-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   83339645 jun 27 18:01 2820/000000927-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  771125073 jun 27 19:01 2820/000000977-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74539638 jun 27 19:00 2820/000000978-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 2147787468 jun 27 19:23 2820/000000993-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  247091510 jun 27 19:23 2820/000000993-000000007.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  196230250 jun 27 19:56 2820/000001025-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88418315 jun 27 20:00 2820/000001029-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  393797547 jun 27 20:52 2820/000001073-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89549315 jun 27 20:56 2820/000001077-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79435020 jun 27 20:58 2820/000001079-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80576485 jun 27 21:01 2820/000001081-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90390351 jun 27 21:01 2820/000001081-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  568972774 jun 27 21:49 2820/000001121-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87610967 jun 27 21:52 2820/000001125-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86009740 jun 27 21:57 2820/000001129-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   77927552 jun 27 21:59 2820/000001131-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   71288630 jun 27 22:00 2820/000001132-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  746058815 jun 27 22:45 2820/000001169-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90185682 jun 27 22:48 2820/000001173-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86567982 jun 27 22:53 2820/000001177-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   85987626 jun 27 22:57 2820/000001181-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   77072479 jun 27 23:00 2820/000001183-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73286098 jun 27 23:01 2820/000001184-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  960236149 jun 28 00:00 2820/000001233-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   70560830 jun 27 23:59 2820/000001234-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  277177040 jun 28 00:56 2827/000000048-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89598314 jun 28 01:00 2827/000000052-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  486035409 jun 28 01:53 2827/000000096-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88902965 jun 28 01:56 2827/000000100-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78652404 jun 28 01:58 2827/000000102-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   71532270 jun 28 02:00 2827/000000103-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73134488 jun 28 02:01 2827/000000104-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  701991306 jun 28 02:49 2827/000000144-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90823301 jun 28 02:52 2827/000000148-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90519359 jun 28 02:57 2827/000000152-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79814612 jun 28 02:59 2827/000000154-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73057816 jun 28 03:00 2827/000000155-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  294271806 jun 28 03:44 2827/000000192-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92988606 jun 28 03:48 2827/000000196-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90290611 jun 28 03:53 2827/000000200-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90171875 jun 28 03:58 2827/000000204-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79597436 jun 28 04:00 2827/000000206-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  984472533 jun 28 04:04 2827/000000208-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  285218814 jun 28 04:59 2827/000000256-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   81084684 jun 28 05:00 2827/000000258-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1417399416 jun 28 05:57 2827/000000304-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91255677 jun 28 05:59 2827/000000308-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73309243 jun 28 06:00 2827/000000309-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   82586237 jun 28 06:01 2827/000000310-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  291603611 jun 28 06:51 2827/000000352-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91951361 jun 28 06:55 2827/000000356-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92554948 jun 28 07:00 2827/000000360-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   75821151 jun 28 07:01 2827/000000361-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  511691658 jun 28 07:47 2827/000000400-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91069637 jun 28 07:51 2827/000000404-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89832995 jun 28 07:56 2827/000000408-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90978181 jun 28 08:00 2827/000000412-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 2073208850 jun 28 08:47 2827/000000448-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   94500932 jun 28 08:47 2827/000000452-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91718347 jun 28 08:52 2827/000000456-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91800071 jun 28 08:56 2827/000000460-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   81137680 jun 28 08:58 2827/000000462-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   82971336 jun 28 09:01 2827/000000464-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  150299750 jun 28 09:01 2827/000000464-000000004.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  364180684 jun 28 09:58 2827/000000512-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80707550 jun 28 09:59 2827/000000514-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74218519 jun 28 10:00 2827/000000515-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  563773556 jun 28 10:54 2827/000000560-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91590275 jun 28 10:58 2827/000000564-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   82358907 jun 28 11:00 2827/000000566-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  790319934 jun 28 11:50 2827/000000608-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91733245 jun 28 11:54 2827/000000612-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91408121 jun 28 11:58 2827/000000616-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   82114817 jun 28 12:00 2827/000000618-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   76664706 jun 28 12:02 2827/000000619-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1004159631 jun 28 12:47 2827/000000656-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   95713708 jun 28 12:50 2827/000000660-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91086058 jun 28 12:54 2827/000000664-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90557062 jun 28 12:59 2827/000000668-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74562794 jun 28 13:00 2827/000000669-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  919225188 jun 28 13:10 2827/000000672-000000007.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  263158559 jun 28 14:00 2827/000000720-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   75726232 jun 28 14:01 2827/000000721-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  442670646 jun 28 14:56 2827/000000768-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88618883 jun 28 15:00 2827/000000772-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  629915374 jun 28 15:53 2827/000000816-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88984229 jun 28 15:56 2827/000000820-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79791667 jun 28 15:58 2827/000000822-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   81958414 jun 28 16:01 2827/000000824-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  802761951 jun 28 16:49 2827/000000864-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88235851 jun 28 16:52 2827/000000868-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88326857 jun 28 16:57 2827/000000872-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79878245 jun 28 16:59 2827/000000874-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   75075596 jun 28 17:00 2827/000000875-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  974084876 jun 28 17:45 2827/000000912-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91440899 jun 28 17:48 2827/000000916-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89021852 jun 28 17:53 2827/000000920-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88316431 jun 28 17:58 2827/000000924-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79680866 jun 28 18:00 2827/000000926-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   76289343 jun 28 18:01 2827/000000927-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1214006718 jun 28 19:00 2827/000000976-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80506666 jun 28 19:00 2827/000000978-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1381218487 jun 28 19:57 2827/000001024-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88053100 jun 28 19:59 2827/000001028-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73138321 jun 28 20:00 2827/000001029-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1575688393 jun 28 20:53 2827/000001072-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89599779 jun 28 20:55 2827/000001076-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87911899 jun 28 21:00 2827/000001080-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74259686 jun 28 21:01 2827/000001081-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  245075149 jun 28 21:47 2827/000001120-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88072490 jun 28 21:51 2827/000001124-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86762911 jun 28 21:56 2827/000001128-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86843253 jun 28 22:00 2827/000001132-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  405736912 jun 28 22:43 2827/000001168-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88986405 jun 28 22:47 2827/000001172-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86576985 jun 28 22:52 2827/000001176-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   85853538 jun 28 22:56 2827/000001180-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   76903237 jun 28 22:58 2827/000001182-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   71704142 jun 28 23:00 2827/000001183-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73231035 jun 28 23:01 2827/000001184-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79554012 jun 28 23:01 2827/000001184-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  628184819 jun 28 23:58 2827/000001232-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   76594258 jun 28 23:59 2827/000001234-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  273782728 jun 29 00:56 2834/000000048-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89535287 jun 29 01:00 2834/000000052-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  480652627 jun 29 01:53 2834/000000096-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88559267 jun 29 01:56 2834/000000100-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78807890 jun 29 01:58 2834/000000102-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   71934685 jun 29 02:00 2834/000000103-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73817871 jun 29 02:01 2834/000000104-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  700284004 jun 29 02:49 2834/000000144-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89663196 jun 29 02:52 2834/000000148-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90125942 jun 29 02:57 2834/000000152-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79352250 jun 29 02:59 2834/000000154-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73511830 jun 29 03:00 2834/000000155-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  291335555 jun 29 03:44 2834/000000192-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   93796210 jun 29 03:48 2834/000000196-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90583207 jun 29 03:53 2834/000000200-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91228648 jun 29 03:58 2834/000000204-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80500998 jun 29 04:00 2834/000000206-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  981346884 jun 29 04:04 2834/000000208-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  276321185 jun 29 04:59 2834/000000256-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   81353494 jun 29 05:00 2834/000000258-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1406919888 jun 29 05:57 2834/000000304-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92049473 jun 29 05:59 2834/000000308-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73437235 jun 29 06:00 2834/000000309-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   83086200 jun 29 06:01 2834/000000310-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  299568525 jun 29 06:51 2834/000000352-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90993881 jun 29 06:55 2834/000000356-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91366978 jun 29 07:00 2834/000000360-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74118382 jun 29 07:01 2834/000000361-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  517728955 jun 29 07:47 2834/000000400-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90451081 jun 29 07:51 2834/000000404-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88581536 jun 29 07:56 2834/000000408-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88854064 jun 29 08:00 2834/000000412-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 2063421439 jun 29 08:47 2834/000000448-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   91491904 jun 29 08:47 2834/000000452-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89364810 jun 29 08:52 2834/000000456-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87270219 jun 29 08:56 2834/000000460-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78001729 jun 29 08:58 2834/000000462-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79755733 jun 29 09:01 2834/000000464-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  140564220 jun 29 09:01 2834/000000464-000000004.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  343351897 jun 29 09:58 2834/000000512-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   77962356 jun 29 09:59 2834/000000514-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   72236780 jun 29 10:00 2834/000000515-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  552318788 jun 29 10:54 2834/000000560-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89439269 jun 29 10:58 2834/000000564-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79277129 jun 29 11:00 2834/000000566-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  780633307 jun 29 11:50 2834/000000608-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90442167 jun 29 11:54 2834/000000612-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89368026 jun 29 11:58 2834/000000616-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79282721 jun 29 12:00 2834/000000618-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74388749 jun 29 12:02 2834/000000619-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  984884648 jun 29 12:47 2834/000000656-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92200478 jun 29 12:50 2834/000000660-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88574952 jun 29 12:54 2834/000000664-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87637088 jun 29 12:59 2834/000000668-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   72577658 jun 29 13:00 2834/000000669-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  887921713 jun 29 13:10 2834/000000672-000000007.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  267031305 jun 29 14:00 2834/000000720-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74136022 jun 29 14:01 2834/000000721-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  452513133 jun 29 14:56 2834/000000768-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87454013 jun 29 15:00 2834/000000772-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  637484168 jun 29 15:53 2834/000000816-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86903288 jun 29 15:56 2834/000000820-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78558221 jun 29 15:58 2834/000000822-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80363252 jun 29 16:01 2834/000000824-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  806590248 jun 29 16:49 2834/000000864-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86818806 jun 29 16:52 2834/000000868-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87121301 jun 29 16:57 2834/000000872-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78602852 jun 29 16:59 2834/000000874-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   72978857 jun 29 17:00 2834/000000875-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  976471478 jun 29 17:45 2834/000000912-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90443617 jun 29 17:48 2834/000000916-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87077133 jun 29 17:53 2834/000000920-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87010850 jun 29 17:58 2834/000000924-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78370088 jun 29 18:00 2834/000000926-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74421903 jun 29 18:01 2834/000000927-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1214830713 jun 29 19:00 2834/000000976-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78684001 jun 29 19:01 2834/000000978-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1381465480 jun 29 19:57 2834/000001024-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   85990980 jun 29 19:59 2834/000001028-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   71923886 jun 29 20:00 2834/000001029-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1576582375 jun 29 20:53 2834/000001072-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86186266 jun 29 20:55 2834/000001076-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86386414 jun 29 21:00 2834/000001080-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   72601536 jun 29 21:01 2834/000001081-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  241119166 jun 29 21:47 2834/000001120-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   86161189 jun 29 21:51 2834/000001124-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   84379928 jun 29 21:56 2834/000001128-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   84987353 jun 29 22:00 2834/000001132-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  399738501 jun 29 22:43 2834/000001168-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87344487 jun 29 22:47 2834/000001172-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   84485673 jun 29 22:52 2834/000001176-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   84531728 jun 29 22:56 2834/000001180-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   75769279 jun 29 22:58 2834/000001182-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   68976428 jun 29 23:00 2834/000001183-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   71402647 jun 29 23:01 2834/000001184-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  621884852 jun 29 23:58 2834/000001232-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   75107251 jun 29 23:59 2834/000001234-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  272314732 jun 30 00:56 2841/000000048-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88196855 jun 30 01:00 2841/000000052-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  478896687 jun 30 01:53 2841/000000096-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87571060 jun 30 01:56 2841/000000100-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   76685625 jun 30 01:58 2841/000000102-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   70444663 jun 30 02:00 2841/000000103-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   72042834 jun 30 02:01 2841/000000104-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  698966367 jun 30 02:49 2841/000000144-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89042488 jun 30 02:52 2841/000000148-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89042924 jun 30 02:57 2841/000000152-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   78257806 jun 30 02:59 2841/000000154-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   71176504 jun 30 03:00 2841/000000155-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  287708936 jun 30 03:44 2841/000000192-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90648844 jun 30 03:48 2841/000000196-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   87013591 jun 30 03:53 2841/000000200-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88047197 jun 30 03:58 2841/000000204-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   77764605 jun 30 04:00 2841/000000206-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  972858060 jun 30 04:04 2841/000000208-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  276329328 jun 30 04:58 2841/000000256-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   77548126 jun 30 05:00 2841/000000258-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 1395513825 jun 30 05:57 2841/000000304-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90103095 jun 30 05:58 2841/000000308-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80700584 jun 30 06:01 2841/000000310-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  298251303 jun 30 06:50 2841/000000352-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90280538 jun 30 06:54 2841/000000356-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90936748 jun 30 06:59 2841/000000360-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   72974829 jun 30 07:00 2841/000000361-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  514585947 jun 30 07:47 2841/000000400-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90906999 jun 30 07:50 2841/000000404-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88717962 jun 30 07:55 2841/000000408-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   88171105 jun 30 08:00 2841/000000412-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   74037841 jun 30 08:01 2841/000000413-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb 2056861232 jun 30 08:46 2841/000000448-000000006.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  145072352 jun 30 09:01 2841/000000464-000000004.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  351610455 jun 30 09:57 2841/000000512-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   77868190 jun 30 09:59 2841/000000514-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   72689643 jun 30 10:00 2841/000000515-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  554339937 jun 30 10:53 2841/000000560-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90637620 jun 30 10:57 2841/000000564-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   79734349 jun 30 10:59 2841/000000566-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   73501041 jun 30 11:00 2841/000000567-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  779781326 jun 30 11:50 2841/000000608-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90395677 jun 30 11:53 2841/000000612-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   90213965 jun 30 11:58 2841/000000616-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   80266678 jun 30 12:00 2841/000000618-000000002.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   75254165 jun 30 12:01 2841/000000619-000000001.tsm.tmp
-rw-r--r-- 1 influxdb influxdb  993448373 jun 30 12:46 2841/000000656-000000005.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   92985140 jun 30 12:49 2841/000000660-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89478146 jun 30 12:54 2841/000000664-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   89329011 jun 30 12:58 2841/000000668-000000003.tsm.tmp
-rw-r--r-- 1 influxdb influxdb   81149708 jun 30 13:01 2841/000000670-000000002.tsm.tmp

`

**Comment by jwilder** [comment]
@forsberg Are you still seeing this issue with 1.3.2 or later?

**Comment by forsberg** [comment]
Well, there's a bunch of them lying around, but there has been no incidents where it's been consuming all the disk during the last ~6 weeks.

Current list of files below. Is it normal to see files which are almost 24h old? 

    root@ospmon01:/var/lib/influxdb/data/telegraf/default# date ; ls -l */*.tsm.tmp  
    tis 15 aug 2017 07:11:36 UTC
    -rw-r--r-- 1 influxdb influxdb  492694570 aug 14 08:58 3186/000000529-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   94490937 aug 14 08:59 3186/000000531-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   86181440 aug 14 09:00 3186/000000532-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   96934878 aug 14 09:01 3186/000000533-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  732211676 aug 14 09:46 3186/000000577-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  110921657 aug 14 09:49 3186/000000581-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106569524 aug 14 09:53 3186/000000585-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  107157725 aug 14 09:57 3186/000000589-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   94418497 aug 14 09:59 3186/000000591-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   86664742 aug 14 10:00 3186/000000592-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   87511291 aug 14 10:01 3186/000000593-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb 1043865073 aug 14 10:51 3186/000000641-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106781942 aug 14 10:53 3186/000000645-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  107274131 aug 14 10:57 3186/000000649-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   94273028 aug 14 10:59 3186/000000651-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   86776225 aug 14 11:00 3186/000000652-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   87993155 aug 14 11:01 3186/000000653-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb 1117785646 aug 14 11:07 3186/000000657-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  323188308 aug 14 11:54 3186/000000705-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106311228 aug 14 11:57 3186/000000709-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   94829872 aug 14 11:59 3186/000000711-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   85503909 aug 14 12:00 3186/000000712-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  109153956 aug 14 12:01 3186/000000713-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb 1642927167 aug 14 13:01 3186/000000769-000000006.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   94524073 aug 14 12:59 3186/000000771-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   86332339 aug 14 13:00 3186/000000772-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  303073809 aug 14 13:46 3186/000000817-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  109478809 aug 14 13:49 3186/000000821-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106242012 aug 14 13:53 3186/000000825-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  104944736 aug 14 13:57 3186/000000829-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   93765231 aug 14 13:59 3186/000000831-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   86219398 aug 14 14:00 3186/000000832-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  592576028 aug 14 14:50 3186/000000881-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106557514 aug 14 14:53 3186/000000885-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106584177 aug 14 14:57 3186/000000889-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   94336943 aug 14 14:59 3186/000000891-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   87050555 aug 14 15:00 3186/000000892-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   88500505 aug 14 15:01 3186/000000893-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  108662059 aug 14 15:01 3186/000000893-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb 2147844240 aug 14 15:42 3186/000000929-000000006.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  240254672 aug 14 15:42 3186/000000929-000000007.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  170181218 aug 14 15:53 3186/000000945-000000004.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  107790186 aug 14 15:57 3186/000000949-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   95071813 aug 14 15:59 3186/000000951-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   97065295 aug 14 16:01 3186/000000953-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  454975534 aug 14 16:58 3186/000001009-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   93850412 aug 14 16:59 3186/000001011-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   86339615 aug 14 17:00 3186/000001012-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   89380851 aug 14 17:01 3186/000001013-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  662339531 aug 14 17:46 3186/000001057-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  110813886 aug 14 17:49 3186/000001061-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106877667 aug 14 17:53 3186/000001065-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106693361 aug 14 17:57 3186/000001069-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   94735204 aug 14 17:59 3186/000001071-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   97721240 aug 14 18:01 3186/000001073-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  168384527 aug 14 18:01 3186/000001073-000000004.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  966454301 aug 14 18:51 3186/000001121-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  108347572 aug 14 18:53 3186/000001125-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  108454781 aug 14 18:57 3186/000001129-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   95272431 aug 14 18:59 3186/000001131-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   97101058 aug 14 19:01 3186/000001133-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb 1240012108 aug 14 19:55 3186/000001185-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  103641103 aug 14 19:57 3186/000001189-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   92599972 aug 14 19:59 3186/000001191-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   84709320 aug 14 20:00 3186/000001192-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   87292176 aug 14 20:01 3186/000001193-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb 1384243296 aug 14 20:18 3186/000001201-000000007.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  288563648 aug 14 20:58 3186/000001249-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   90273053 aug 14 20:59 3186/000001251-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   83435919 aug 14 21:00 3186/000001252-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   85981074 aug 14 21:01 3186/000001253-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  104002833 aug 14 21:01 3186/000001253-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  462053561 aug 14 21:46 3186/000001297-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  104272703 aug 14 21:49 3186/000001301-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  100538087 aug 14 21:53 3186/000001305-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  100515429 aug 14 21:57 3186/000001309-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   89641379 aug 14 21:59 3186/000001311-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   82402674 aug 14 22:00 3186/000001312-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   84532856 aug 14 22:01 3186/000001313-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  691095406 aug 14 22:51 3186/000001361-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  100672431 aug 14 22:54 3186/000001365-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  100485341 aug 14 22:58 3186/000001369-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   89756029 aug 14 23:00 3186/000001371-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   83015140 aug 14 23:01 3186/000001372-000000001.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  938936209 aug 14 23:59 3186/000001425-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   88777808 aug 15 00:00 3186/000001427-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  292443959 aug 15 00:50 3198/000000048-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  101411511 aug 15 00:54 3198/000000052-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  101943511 aug 15 00:58 3198/000000056-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   89332987 aug 15 01:00 3198/000000058-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  505550708 aug 15 01:40 3198/000000096-000000006.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  160001437 aug 15 01:55 3198/000000112-000000004.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  102208800 aug 15 01:59 3198/000000116-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   91004981 aug 15 02:00 3198/000000118-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  714394970 aug 15 02:28 3198/000000144-000000006.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  236597778 aug 15 02:59 3198/000000176-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   92653760 aug 15 03:01 3198/000000178-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb 1005245073 aug 15 03:33 3198/000000208-000000006.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  165436939 aug 15 03:47 3198/000000224-000000004.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  104342865 aug 15 03:51 3198/000000228-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  104294184 aug 15 03:55 3198/000000232-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  104928995 aug 15 03:59 3198/000000236-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   93000214 aug 15 04:00 3198/000000238-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  459501623 aug 15 04:51 3198/000000288-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  104650801 aug 15 04:55 3198/000000292-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  102920685 aug 15 04:59 3198/000000296-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   92619804 aug 15 05:00 3198/000000298-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  325537861 aug 15 05:55 3198/000000352-000000005.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb  106219979 aug 15 05:59 3198/000000356-000000003.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   95086181 aug 15 06:00 3198/000000358-000000002.tsm.tmp
    -rw-r--r-- 1 influxdb influxdb   95670251 aug 15 07:01 3198/000000418-000000002.tsm.tmp

**Comment by stuartcarnie** [comment]
@forsberg can you grab a goroutine dump on that server using the following command

```
curl -o goroutine.txt http://<server>:8086/debug/pprof/goroutine\?debug=1
```

and attach it to this issue

**Comment by jwilder** [comment]
@forsberg Would you be able to test w/ 1.3.2?  There is at least one change related to lingering tmp files that landed after the build you are running (https://github.com/influxdata/influxdb/pull/8562).

**Comment by forsberg** [comment]
OK, so still on 1.4.0-n201706260800-0:
[current-files.txt](https://github.com/influxdata/influxdb/files/1227559/current-files.txt)
[goroutine.txt](https://github.com/influxdata/influxdb/files/1227558/goroutine.txt)



    root@ospmon01:/var/lib/influxdb/data/telegraf/default# COLUMNS=200  dpkg -l influxdb ; date ; ls -l */*.tsm.tmp > /var/tmp/current-files.txt ; curl -q -o /var/tmp/goroutine.txt https://ospmon01.opera.com:8086/debug/pprof/goroutine\?debug=1
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name                                         Version                     Architecture                Description
    +++-============================================-===========================-===========================-=============================================================================================
    ii  influxdb                                     1.4.0~n201706260800-0       amd64                       Distributed time-series database.
    ons 16 aug 2017 08:35:45 UTC
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 38889    0 38889    0     0   423k      0 --:--:-- --:--:-- --:--:--  426k

**Comment by forsberg** [comment]
There's no risk in downgrading that snapshot to 1.3.2? 

Not sure I'll find the time for that, but maybe.

**Comment by jwilder** [comment]
@forsberg We have another fix in progress here: https://github.com/influxdata/influxdb/pull/8706

**Comment by stuartcarnie** [comment]
@forsberg no need to downgrade if you are running master. If that server still has open `tsm.tmp` files can you also grab a heap and block profile:

```
$ curl -o block.txt http://<server>:8086/debug/pprof/block\?debug=1
$ curl -o heap.txt http://<server>:8086/debug/pprof/heap\?debug=1
```

Thanks!

**Comment by stuartcarnie** [comment]
@forsberg, a few more questions:

* how many cores on that machine
* run `influx 0-execute 'SHOW SHARDS'` and include that output, assuming none of the names (databases and retention policies) are sensitive

**Comment by e-dard** [comment]
@stuartcarnie have we resolved this?

**Comment by stuartcarnie** [comment]
@e-dard yes
