### ISSUE TITLE
Lost all datas after DELETE command

### ISSUE THREAD

**Issue by max3163** [influxdata/influxdb#8822]
### Bug report
Influxdb version = 1.3.5
On linux go1.8.3
Intel(R) Xeon(R) CPU E5-2620 with 64Go of RAM

Sometimes, when we try to delete somes points on a specific measurement , we lost 2 or 3 days of datas in our database. ( all measurements are impacted ! )

Exemple of DELETE query  : 

DELETE FROM events WHERE application = 'cosmos' AND time < 1505223439180000001 AND time > 1505223439179999999

Same issue with :

DELETE FROM events WHERE application = 'cosmos' AND time = 1505223439180000000

You can find a extract log when the issue appear with many messages about full compaction aborted... 
If you need a more details logs , tell me.
We have many application which write data in parallel.

[delete.zip](https://github.com/influxdata/influxdb/files/1298810/delete.zip)

**Comment by e-dard** [comment]
@max3163 are you saying that you have points in the `events` metric that are outside the time window `[1505223439180000001, 1505223439179999999]` and are deleted?

**Comment by max3163** [comment]
Not really, I'm saying that I lost most of the time last 3 days of datas points in all my measurements present in the same database that the 'events' metric.

**Comment by e-dard** [comment]
So you're saying that within the specified time window you have lost points that belong to a series that doesn't have the `application=cosmos` tag pair?

**Comment by max3163** [comment]
Yes exactly !
We lost all datas points on the database 'qualif' for a period of time of about 3 days. 
All tag pair are impacted and some measurements don't have the application tag at all.

**Comment by jwilder** [comment]
This should be fixed by #8981.

**Comment by max3163** [comment]
I've test the latest version of Influxb with your fix but I still have the issue. 
See in attachment a new log file, the issue appear when I start delete 10 points in a row at '2017-11-13T16:16:22Z'

After that, one week of data is lost in all the database.
The issue appear in our backup server with no writer just some queries from grafana.

[log2.txt](https://github.com/influxdata/influxdb/files/1470101/log2.txt)

Can you re-open the bug ? Or I need to create a new one ?

**Comment by daviskirk** [comment]
Same here!
